from dataclasses import dataclass

from xdsl.context import Context
from xdsl.dialects import arith, builtin, func, llvm, memref, scf
from xdsl.dialects.builtin import DYNAMIC_INDEX, IndexType, IntegerAttr, StringAttr, i8
from xdsl.ir import Block, Region
from xdsl.passes import ModulePass
from xdsl.utils.hints import isa

from xdsl_ccpp.dialects import ccpp
from xdsl_ccpp.dialects.ccpp_utils import (
    ArraySectionOp,
    HostVarRefOp,
    SetStringOp,
    StrCmpOp,
    SuiteVariablesOp,
    TrimOp,
    WriteErrMsgOp,
)
from xdsl_ccpp.transforms.util.ccpp_descriptors import (
    BuildMetaDataDescriptions,
    BuildSchemeDescription,
    CCPPType,
)
from xdsl_ccpp.transforms.util.typing import TypeConversions


@dataclass(frozen=True)
class CCPPCAP(ModulePass):
    """MLIR pass that generates a single combined CCPP physics cap dispatcher module.

    Runs after generate-suite-cap.  For all suites found in the ccpp module,
    generates a single named ModuleOp containing lifecycle dispatcher subroutines
    that use nested if/else chains on ``suite_name`` to dispatch to the appropriate
    suite cap subroutine (generated by generate-suite-cap).

    Output is one ModuleOp (e.g. ``test_host_ccpp_cap``) inserted into the
    top-level module alongside the suite cap modules.
    """

    name = "generate-ccpp-cap"

    # Optional override for the CamelCase host name prefix applied to all
    # generated lifecycle subroutines.  When absent, the prefix is derived
    # automatically from the first suite name (e.g. hello_world_suite → HelloWorld).
    host_name: str = ""

    def find_ccpp_module(self, ops):
        """Return the named 'ccpp' ModuleOp from the given op list, or None."""
        for op in ops:
            if (
                isa(op, builtin.ModuleOp)
                and op.sym_name is not None
                and op.sym_name.data == "ccpp"
            ):
                return op
        return None

    def _collect_public_suite_functions(self, ops):
        """Scan all named ModuleOps in ops and return a map of public function info.

        Returns:
            dict mapping function_name → (module_name, output_types,
            input_types, input_names).
        """
        public_fns = {}
        for op in ops:
            if not (isa(op, builtin.ModuleOp) and op.sym_name is not None):
                continue
            mod_name = op.sym_name.data
            for child in op.body.block.ops:
                if (
                    isa(child, func.FuncOp)
                    and not child.is_declaration
                    and child.sym_visibility is not None
                    and child.sym_visibility.data == "public"
                ):
                    public_fns[child.sym_name.data] = (
                        mod_name,
                        list(child.function_type.outputs),
                        list(child.function_type.inputs),
                        [arg.name_hint for arg in child.body.block.args],
                    )
        return public_fns

    def _derive_camel_case_name(self, suite_name: str) -> str:
        """Convert a snake_case suite name to CamelCase, stripping any '_suite' suffix."""
        name = suite_name
        if name.endswith("_suite"):
            name = name[:-6]
        return "".join(word.capitalize() for word in name.split("_"))

    def _build_suite_variables_fn(self, suite_descriptions, ccpp_mod,
                                   host_std_names, protected_std_names) -> "SuiteVariablesOp":
        """Build the ccpp_physics_suite_variables subroutine for all suites.

        Scans the MLIR IR directly (ArgumentOp properties) rather than going
        through the descriptor layer, avoiding subtle descriptor-build issues.

        Filtering rules (applied per ArgumentOp):
        - Skip if is_interstitial is set (scheme-internal variable)
        - Skip if standard_name is in _CCPP_INTERNAL (framework scalars)
        - Skip if standard_name is in protected_std_names (dimension params)
        - ccpp_error_code/ccpp_error_message always go to output-only
        - Skip if standard_name not in host_std_names (no host counterpart)
        - Arrays (dimensions > 0) go to both input and output
        - Scalars go to input/output/both by declared intent
        - Union across all entry points (_init, _run, _finalize, etc.)
        """
        _CCPP_ERR = frozenset({"ccpp_error_code", "ccpp_error_message"})
        _INTERNAL = frozenset({
            "horizontal_loop_extent",
            "ccpp_constituents",
            "ccpp_constituent_tendencies",
        })
        CM = 36  # character length matching cm=36 in test driver

        suite_vars: dict = {}
        for suite_name, suite_desc in suite_descriptions.items():
            # Collect the set of scheme names belonging to this suite
            scheme_names: set = set()
            for group in suite_desc:
                for scheme in group:
                    scheme_names.add(scheme.attributes["name"])

            input_vars: set = set()
            output_vars: set = set()

            # Scan scheme TablePropertiesOp nodes in the IR directly
            for tbl_op in ccpp_mod.body.ops:
                if not isa(tbl_op, ccpp.TablePropertiesOp):
                    continue
                if tbl_op.table_type.data != "scheme":
                    continue
                if tbl_op.table_name.data not in scheme_names:
                    continue

                # Iterate all entry-point arg tables (_init, _run, _finalize …)
                for arg_table_op in tbl_op.body.ops:
                    if not isa(arg_table_op, ccpp.ArgumentTableOp):
                        continue

                    for arg_op in arg_table_op.body.ops:
                        if not isa(arg_op, ccpp.ArgumentOp):
                            continue

                        # Read all properties directly from the dict to avoid
                        # any issues with xDSL's formal property accessor layer.
                        sn_prop = arg_op.properties.get("standard_name")
                        if sn_prop is None:
                            continue
                        std_name = sn_prop.data.lower()

                        # is_interstitial: UnitAttr when set, None when absent
                        is_int = arg_op.properties.get("is_interstitial")
                        if is_int is not None:
                            continue
                        if std_name in _INTERNAL:
                            continue
                        if std_name in protected_std_names:
                            continue

                        # Error flags → output-only special case
                        if std_name in _CCPP_ERR:
                            output_vars.add(std_name)
                            continue

                        # Exclude args with no matching host variable
                        if std_name not in host_std_names:
                            continue

                        # intent: StringAttr when set
                        intent_prop = arg_op.properties.get("intent")
                        intent = intent_prop.data.lower() if intent_prop is not None else None

                        # dimensions: IntAttr (0 = scalar, absent = scalar)
                        dims_prop = arg_op.properties.get("dimensions")
                        has_dims = (
                            dims_prop is not None and dims_prop.data > 0
                        )

                        if has_dims:
                            # Arrays are always pass-by-reference in Fortran
                            input_vars.add(std_name)
                            output_vars.add(std_name)
                        else:
                            if intent in ("in", "inout"):
                                input_vars.add(std_name)
                            if intent in ("out", "inout"):
                                output_vars.add(std_name)

            required_vars = input_vars | output_vars
            suite_vars[suite_name] = (
                sorted(input_vars),
                sorted(output_vars),
                sorted(required_vars),
            )

        # Build the complete Fortran subroutine as a Python string
        lines: list[str] = []
        lines.append(
            "subroutine ccpp_physics_suite_variables"
            "(suite_name, var_list, errmsg, errflg, input_vars, output_vars)"
        )
        lines.append("  character(len=*), intent(in) :: suite_name")
        lines.append("  character(len=*), allocatable, intent(out) :: var_list(:)")
        lines.append("  character(len=512), intent(out) :: errmsg")
        lines.append("  integer, intent(out) :: errflg")
        lines.append("  logical, optional, intent(in) :: input_vars")
        lines.append("  logical, optional, intent(in) :: output_vars")
        lines.append("  logical :: do_input, do_output")
        lines.append("  errmsg = ''")
        lines.append("  errflg = 0")
        lines.append("  do_input = .true.")
        lines.append("  do_output = .true.")
        lines.append("  if (present(input_vars)) do_input = input_vars")
        lines.append("  if (present(output_vars)) do_output = output_vars")

        for idx, (suite_name, (in_v, out_v, req_v)) in enumerate(suite_vars.items()):
            kw = "if" if idx == 0 else "else if"
            lines.append(f"  {kw} (trim(suite_name) .eq. '{suite_name}') then")
            for branch_name, var_list in (
                ("input only",  "do_input .and. .not. do_output"),
                ("output only", ".not. do_input .and. do_output"),
                ("required",    None),
            ):
                if branch_name == "input only":
                    lines.append(f"    if ({var_list}) then")
                    vlist = in_v
                elif branch_name == "output only":
                    lines.append(f"    else if ({var_list}) then")
                    vlist = out_v
                else:
                    lines.append("    else")
                    vlist = req_v
                lines.append(f"      allocate(var_list({len(vlist)}))")
                for j, v in enumerate(vlist):
                    lines.append(f"      var_list({j + 1}) = '{v:<{CM}}'")
            lines.append("    end if")

        lines.append("  else")
        lines.append(
            '    write(errmsg, \'(3a)\') "No suite named ", trim(suite_name), " found"'
        )
        lines.append("    errflg = 1")
        lines.append("  end if")
        lines.append("end subroutine ccpp_physics_suite_variables")

        return SuiteVariablesOp("\n".join(lines))

    def _get_suite_lifecycle_return_types(self, scheme_names, meta_data, table_postfix):
        """Derive the ordered return types of a suite lifecycle subroutine."""
        all_out_args = {}
        for scheme_name in scheme_names:
            table_name = scheme_name + table_postfix
            if table_name not in meta_data[scheme_name].arg_tables:
                continue
            arg_table = meta_data[scheme_name].getArgTable(table_name)
            for fn_arg in arg_table.getFunctionArguments():
                if (
                    fn_arg.getAttr("intent") == "out"
                    and fn_arg.name not in all_out_args
                ):
                    all_out_args[fn_arg.name] = fn_arg

        return [
            TypeConversions.convert(
                arg.getAttr("type"),
                arg.getAttr("kind") if arg.hasAttr("kind") else None,
                0,
            )
            for arg in all_out_args.values()
        ]

    def _generate_lifecycle_fn(
        self,
        fn_name,
        suite_entries,
        suite_name_type,
        errmsg_type,
        errflg_type,
        char_base,
        int_base,
        public_fns,
    ):
        """Build one combined CCPP cap lifecycle FuncOp dispatching over all suites.

        ``suite_entries`` is a list of ``(suite_name, suite_callee, call_ret_types)``
        tuples.  Generates a nested if/else chain that checks ``suite_name`` against
        each suite's name literal and calls the corresponding suite cap subroutine.

        Returns ``(FuncOp, [external_decl_FuncOp, ...])``.
        """
        for _, suite_callee, _ in suite_entries:
            assert suite_callee in public_fns, (
                f"Suite callee '{suite_callee}' not found among public suite cap "
                f"functions; available: {sorted(public_fns)}"
            )

        errmsg_alloc = memref.AllocaOp.get(char_base, shape=[512])
        errmsg_alloc.memref.name_hint = "errmsg"
        errflg_alloc = memref.AllocaOp.get(int_base, shape=[])
        errflg_alloc.memref.name_hint = "errflg"

        new_block = Block(arg_types=[suite_name_type])
        new_block.args[0].name_hint = "suite_name"

        err_const = arith.ConstantOp.from_int_and_width(0, 32)
        store_errflg = memref.StoreOp.get(err_const, errflg_alloc, [])

        trim_suite_name = TrimOp(new_block.args[0])

        # Innermost else: no suite matched
        write_err = WriteErrMsgOp(
            errmsg_alloc, trim_suite_name.res, "No suite named ", "found"
        )
        one_err = arith.ConstantOp.from_int_and_width(1, 32)
        store_errflg_err = memref.StoreOp.get(one_err, errflg_alloc, [])

        # Build nested if/else chain from inside out (reverse iteration)
        current_false_ops = [write_err, one_err, store_errflg_err, scf.YieldOp()]

        for suite_name, suite_callee, call_ret_types in reversed(suite_entries):
            strcmp_op = StrCmpOp(trim_suite_name.res, literal=suite_name)
            call_op = func.CallOp(suite_callee, [], call_ret_types)
            copy_ops = []
            for idx, ret_type in enumerate(call_ret_types):
                if ret_type == errmsg_type:
                    copy_ops.append(memref.CopyOp(call_op.results[idx], errmsg_alloc))
                elif ret_type == errflg_type:
                    copy_ops.append(memref.CopyOp(call_op.results[idx], errflg_alloc))
            if_op = scf.IfOp(
                strcmp_op.res,
                [],
                [call_op] + copy_ops + [scf.YieldOp()],
                current_false_ops,
            )
            current_false_ops = [strcmp_op, if_op, scf.YieldOp()]

        # Strip trailing YieldOp — main block ends with ReturnOp, not YieldOp
        main_chain_ops = current_false_ops[:-1]

        ret_op = func.ReturnOp(errmsg_alloc, errflg_alloc)

        new_block.add_ops(
            [
                errmsg_alloc,
                errflg_alloc,
                err_const,
                store_errflg,
                trim_suite_name,
                *main_chain_ops,
                ret_op,
            ]
        )

        body = Region()
        body.add_block(new_block)

        fn_type = builtin.FunctionType.from_lists(
            [suite_name_type],
            [errmsg_type, errflg_type],
        )
        cap_fn = func.FuncOp(fn_name, fn_type, body, visibility="public")

        decls = []
        for _, suite_callee, call_ret_types in suite_entries:
            callee_module, _, _, _ = public_fns[suite_callee]
            decl = func.FuncOp.external(suite_callee, [], call_ret_types)
            decl.attributes["module"] = StringAttr(callee_module)
            decls.append(decl)

        return cap_fn, decls

    def _generate_run_fn(
        self,
        fn_name,
        suite_run_entries,
        suite_name_type,
        errmsg_type,
        errflg_type,
        char_base,
        int_base,
        public_fns,
        meta_data,
    ):
        """Build the combined CCPP cap physics run FuncOp dispatching over all suites.

        ``suite_run_entries`` is a list of
        ``(suite_name, suite_part, suite_callee, scheme_names)`` tuples.

        The generated function signature uses the union of non-host physics args
        across all suites.  A nested if/else chain on ``suite_name`` dispatches to
        the appropriate suite; each matching branch has an inner if/else on
        ``suite_part``.  Host variable references and array sections are placed
        inside each suite's branch.

        Returns ``(FuncOp, [external_decl_FuncOp, ...], host_global_ops)``.
        """
        for _, _, suite_callee, _ in suite_run_entries:
            assert suite_callee in public_fns, (
                f"Suite callee '{suite_callee}' not found; available: {sorted(public_fns)}"
            )

        suite_part_type = suite_name_type

        # ── Build {standard_name → (host_var_name, module_name)} from MODULE metadata ──
        host_var_map = {}
        for tbl_name, props in meta_data.items():
            if props.getAttr("type") != CCPPType.MODULE:
                continue
            if tbl_name not in props.arg_tables:
                continue
            for var in props.getArgTable(tbl_name).getFunctionArguments():
                if var.hasAttr("standard_name"):
                    host_var_map[var.getAttr("standard_name")] = (var.name, tbl_name)

        # ── Per-suite information ──────────────────────────────────────────────
        per_suite = []
        all_host_global_ops: list = []
        seen_host_globals: set = set()

        for suite_name, suite_part, suite_callee, scheme_names in suite_run_entries:
            (
                callee_module,
                callee_output_types,
                callee_input_types,
                callee_input_names,
            ) = public_fns[suite_callee]

            # Build {local_arg_name → standard_name} from the _run arg tables.
            std_name_of = {}
            for scheme_name in scheme_names:
                table_name = scheme_name + "_run"
                if scheme_name not in meta_data:
                    continue
                if table_name not in meta_data[scheme_name].arg_tables:
                    continue
                for fn_arg in (
                    meta_data[scheme_name]
                    .getArgTable(table_name)
                    .getFunctionArguments()
                ):
                    if fn_arg.name not in std_name_of and fn_arg.hasAttr(
                        "standard_name"
                    ):
                        std_name_of[fn_arg.name] = fn_arg.getAttr("standard_name")

            # Classify each callee input arg as host-mapped or plain block arg.
            physics_arg_sources = []
            for arg_name in callee_input_names:
                std_name = std_name_of.get(arg_name)
                if std_name and std_name in host_var_map:
                    host_var_name, host_module_name = host_var_map[std_name]
                    assert host_var_name in (
                        meta_data[host_module_name]
                        .arg_tables[host_module_name]
                        .function_arguments
                    ), (
                        f"Host variable '{host_var_name}' not found in "
                        f"'{host_module_name}' arg table"
                    )
                    physics_arg_sources.append(
                        ("host", host_var_name, host_module_name)
                    )
                else:
                    physics_arg_sources.append(("block",))

            non_host_args = [
                (callee_input_names[i], callee_input_types[i])
                for i, src in enumerate(physics_arg_sources)
                if src[0] == "block"
            ]

            # Collect module-level host global stubs (shared across all suites).
            for i, (_arg_name, _arg_type) in enumerate(
                zip(callee_input_names, callee_input_types)
            ):
                src = physics_arg_sources[i]
                if src[0] != "host":
                    continue
                _, host_var_name, host_module_name = src
                key = (host_var_name, host_module_name)
                if key not in seen_host_globals:
                    seen_host_globals.add(key)
                    glob = llvm.GlobalOp(
                        llvm.LLVMArrayType.from_size_and_type(1, i8),
                        host_var_name,
                        "external",
                    )
                    glob.attributes["module"] = StringAttr(host_module_name)
                    all_host_global_ops.append(glob)

            per_suite.append(
                {
                    "suite_name": suite_name,
                    "suite_part": suite_part,
                    "suite_callee": suite_callee,
                    "callee_module": callee_module,
                    "callee_output_types": callee_output_types,
                    "callee_input_types": callee_input_types,
                    "callee_input_names": callee_input_names,
                    "physics_arg_sources": physics_arg_sources,
                    "non_host_args": non_host_args,
                    "scheme_names": scheme_names,
                }
            )

        # ── Union of non-host args across all suites (ordered by first appearance) ──
        union_non_host_args: dict = {}
        for info in per_suite:
            for arg_name, arg_type in info["non_host_args"]:
                if arg_name not in union_non_host_args:
                    union_non_host_args[arg_name] = arg_type

        n_non_host = len(union_non_host_args)
        all_block_types = (
            [suite_name_type, suite_part_type]
            + list(union_non_host_args.values())
            + [errmsg_type, errflg_type]
        )
        new_block = Block(arg_types=all_block_types)

        suite_name_arg = new_block.args[0]
        suite_name_arg.name_hint = "suite_name"
        suite_part_arg = new_block.args[1]
        suite_part_arg.name_hint = "suite_part"

        block_arg_map = {}
        for i, arg_name in enumerate(union_non_host_args):
            ba = new_block.args[2 + i]
            ba.name_hint = arg_name
            block_arg_map[arg_name] = ba

        errmsg_arg = new_block.args[2 + n_non_host]
        errmsg_arg.name_hint = "errmsg"
        errflg_arg = new_block.args[2 + n_non_host + 1]
        errflg_arg.name_hint = "errflg"

        # ── Main block setup ───────────────────────────────────────────────────
        err_const = arith.ConstantOp.from_int_and_width(0, 32)
        store_errflg = memref.StoreOp.get(err_const, errflg_arg, [])

        trim_suite_name = TrimOp(suite_name_arg)

        # Innermost else: no suite matched
        write_suite_name_err = WriteErrMsgOp(
            errmsg_arg, trim_suite_name.res, "No suite named ", "found"
        )
        one_outer_err = arith.ConstantOp.from_int_and_width(1, 32)
        store_outer_err = memref.StoreOp.get(one_outer_err, errflg_arg, [])

        # ── Build nested if/else chain from inside out ─────────────────────────
        current_false_ops = [
            write_suite_name_err,
            one_outer_err,
            store_outer_err,
            scf.YieldOp(),
        ]
        all_decls = []

        for info in reversed(per_suite):
            suite_name = info["suite_name"]
            suite_part = info["suite_part"]
            suite_callee = info["suite_callee"]
            callee_module = info["callee_module"]
            callee_output_types = info["callee_output_types"]
            callee_input_types = info["callee_input_types"]
            callee_input_names = info["callee_input_names"]
            physics_arg_sources = info["physics_arg_sources"]

            # ── HostVarRefOps for this suite (placed inside the suite's true branch) ──
            host_var_ref_ops = []
            host_var_ref_results = {}
            host_name_to_ref_result = {}

            for i, (arg_name, arg_type) in enumerate(
                zip(callee_input_names, callee_input_types)
            ):
                src = physics_arg_sources[i]
                if src[0] != "host":
                    continue
                _, host_var_name, host_module_name = src
                ref_op = HostVarRefOp(host_var_name, host_module_name, arg_type)
                host_var_ref_ops.append(ref_op)
                host_var_ref_results[arg_name] = ref_op.res
                host_name_to_ref_result[host_var_name] = ref_op.res

            # ── ArraySectionOps for this suite ────────────────────────────────
            array_section_pre_ops = []
            array_section_extra_ops = []
            array_section_main_ops = []
            one_const_for_sections = None

            for i, (arg_name, arg_type) in enumerate(
                zip(callee_input_names, callee_input_types)
            ):
                src = physics_arg_sources[i]
                if src[0] != "host":
                    continue
                _, host_var_name, host_module_name = src

                try:
                    mod_arg_table = meta_data[host_module_name].getArgTable(
                        host_module_name
                    )
                    host_var_desc = mod_arg_table.getFunctionArgument(host_var_name)
                except (KeyError, AssertionError):
                    continue

                if not host_var_desc.hasAttr("dim_names"):
                    continue
                dim_names_list = host_var_desc.getAttr("dim_names")
                if not dim_names_list or dim_names_list[0] != "horizontal_dimension":
                    continue

                if "col_start" not in block_arg_map or "col_end" not in block_arg_map:
                    continue

                lowers = [block_arg_map["col_start"]]
                uppers = [block_arg_map["col_end"]]

                valid = True
                for dim_std_name in dim_names_list[1:]:
                    if dim_std_name not in host_var_map:
                        valid = False
                        break
                    dim_var_name, dim_module_name = host_var_map[dim_std_name]

                    if dim_var_name in host_name_to_ref_result:
                        dim_upper_ref = host_name_to_ref_result[dim_var_name]
                    else:
                        dim_ref_op = HostVarRefOp(
                            dim_var_name,
                            dim_module_name,
                            TypeConversions.getBaseType("integer"),
                        )
                        array_section_extra_ops.append(dim_ref_op)
                        host_name_to_ref_result[dim_var_name] = dim_ref_op.res
                        dim_upper_ref = dim_ref_op.res

                        key = (dim_var_name, dim_module_name)
                        if key not in seen_host_globals:
                            seen_host_globals.add(key)
                            dim_glob = llvm.GlobalOp(
                                llvm.LLVMArrayType.from_size_and_type(1, i8),
                                dim_var_name,
                                "external",
                            )
                            dim_glob.attributes["module"] = StringAttr(dim_module_name)
                            all_host_global_ops.append(dim_glob)

                    if one_const_for_sections is None:
                        one_const_for_sections = arith.ConstantOp.from_int_and_width(
                            1, 32
                        )
                        array_section_pre_ops.append(one_const_for_sections)

                    lowers.append(one_const_for_sections.result)
                    uppers.append(dim_upper_ref)

                if not valid or len(lowers) < 2:
                    continue

                section = ArraySectionOp(
                    host_var_ref_results[arg_name],
                    lowers,
                    uppers,
                )
                array_section_main_ops.append(section)
                host_var_ref_results[arg_name] = section.res

            array_section_ops = (
                array_section_pre_ops + array_section_extra_ops + array_section_main_ops
            )

            # ── Build call args in callee order ───────────────────────────────
            call_args = []
            for i, arg_name in enumerate(callee_input_names):
                if physics_arg_sources[i][0] == "host":
                    call_args.append(host_var_ref_results[arg_name])
                else:
                    call_args.append(block_arg_map[arg_name])

            # ── Inner if for suite_part ────────────────────────────────────────
            trim_suite_part = TrimOp(suite_part_arg)
            suite_part_eq = StrCmpOp(trim_suite_part.res, literal=suite_part)

            call_op = func.CallOp(suite_callee, call_args, callee_output_types)

            copy_ops = []
            for idx, ret_type in enumerate(callee_output_types):
                if ret_type == errmsg_type:
                    copy_ops.append(memref.CopyOp(call_op.results[idx], errmsg_arg))
                elif ret_type == errflg_type:
                    copy_ops.append(memref.CopyOp(call_op.results[idx], errflg_arg))

            write_suite_part = WriteErrMsgOp(
                errmsg_arg,
                trim_suite_part.res,
                "No suite part named ",
                f" found in suite {suite_name}",
            )
            one_inner = arith.ConstantOp.from_int_and_width(1, 32)
            store_errflg_inner = memref.StoreOp.get(one_inner, errflg_arg, [])

            inner_if = scf.IfOp(
                suite_part_eq.res,
                [],
                [call_op] + copy_ops + [scf.YieldOp()],
                [write_suite_part, one_inner, store_errflg_inner, scf.YieldOp()],
            )

            # True branch ops for this suite's outer if
            true_branch_ops = [
                *host_var_ref_ops,
                *array_section_ops,
                trim_suite_part,
                suite_part_eq,
                inner_if,
                scf.YieldOp(),
            ]

            # Outer if for suite_name
            strcmp_op = StrCmpOp(trim_suite_name.res, literal=suite_name)
            if_op = scf.IfOp(
                strcmp_op.res,
                [],
                true_branch_ops,
                current_false_ops,
            )
            current_false_ops = [strcmp_op, if_op, scf.YieldOp()]

            decl = func.FuncOp.external(
                suite_callee, callee_input_types, callee_output_types
            )
            decl.attributes["module"] = StringAttr(callee_module)
            all_decls.append(decl)

        # Strip trailing YieldOp — main block ends with ReturnOp
        main_chain_ops = current_false_ops[:-1]

        ret_op = func.ReturnOp(errmsg_arg, errflg_arg)

        new_block.add_ops(
            [
                err_const,
                store_errflg,
                trim_suite_name,
                *main_chain_ops,
                ret_op,
            ]
        )

        body = Region()
        body.add_block(new_block)

        fn_type = builtin.FunctionType.from_lists(
            all_block_types,
            [errmsg_type, errflg_type],
        )
        cap_fn = func.FuncOp(fn_name, fn_type, body, visibility="public")
        return cap_fn, all_decls, all_host_global_ops

    def _generate_suite_part_list_fn(
        self,
        suite_part_entries,
        inner_char_type,
        allocatable_type,
        suite_name_type,
        errmsg_type,
        errflg_type,
        char_base,
        int_base,
    ):
        """Build the ccpp_physics_suite_part_list FuncOp for all suites.

        ``suite_part_entries`` is a list of ``(suite_name, [part_names])`` tuples.
        Generates a subroutine with a nested if/else chain that checks suite_name
        and fills part_list with the matching suite's part names.

        Returns (FuncOp, list[llvm.GlobalOp]).
        """
        # Collect ALL unique part names for shared global string constants.
        all_part_names = list(
            dict.fromkeys(
                pn for _, part_names in suite_part_entries for pn in part_names
            )
        )

        part_global_ops = []
        part_global_names: dict = {}
        for pn in all_part_names:
            str_global_name = f"str_{pn}"
            arr_type = llvm.LLVMArrayType.from_size_and_type(len(pn), i8)
            part_global_ops.append(
                llvm.GlobalOp(
                    arr_type,
                    str_global_name,
                    "internal",
                    constant=True,
                    value=StringAttr(pn),
                )
            )
            part_global_names[pn] = (str_global_name, arr_type)

        new_block = Block(arg_types=[suite_name_type, allocatable_type])
        new_block.args[0].name_hint = "suite_name"
        new_block.args[1].name_hint = "part_list"

        errmsg_alloc = memref.AllocaOp.get(char_base, shape=[512])
        errmsg_alloc.memref.name_hint = "errmsg"
        errflg_alloc = memref.AllocaOp.get(int_base, shape=[])
        errflg_alloc.memref.name_hint = "errflg"

        err_const = arith.ConstantOp.from_int_and_width(0, 32)
        store_errflg = memref.StoreOp.get(err_const, errflg_alloc, [])

        trim_suite_name = TrimOp(new_block.args[0])

        # Innermost else: no suite matched
        write_err = WriteErrMsgOp(
            errmsg_alloc, trim_suite_name.res, "No suite named ", " found"
        )
        one_err = arith.ConstantOp.from_int_and_width(1, 32)
        store_errflg_err = memref.StoreOp.get(one_err, errflg_alloc, [])

        # Build chain from inside out
        current_false_ops = [write_err, one_err, store_errflg_err, scf.YieldOp()]

        for suite_name, part_names in reversed(suite_part_entries):
            strcmp_op = StrCmpOp(trim_suite_name.res, literal=suite_name)

            true_ops = []
            for pn in part_names:
                str_global_name, arr_type = part_global_names[pn]
                str_len_const = arith.ConstantOp(
                    IntegerAttr(len(pn), IndexType()), IndexType()
                )
                str_alloc = memref.AllocOp([str_len_const.result], [], inner_char_type)
                addr_op = llvm.AddressOfOp(str_global_name, llvm.LLVMPointerType())
                load_op = llvm.LoadOp(addr_op, arr_type)
                set_str_op = SetStringOp(str_alloc.memref, load_op.dereferenced_value)
                store_ref_op = memref.StoreOp.get(
                    str_alloc.memref, new_block.args[1], []
                )
                true_ops.extend(
                    [
                        str_len_const,
                        str_alloc,
                        addr_op,
                        load_op,
                        set_str_op,
                        store_ref_op,
                    ]
                )
            true_ops.append(scf.YieldOp())

            if_op = scf.IfOp(strcmp_op.res, [], true_ops, current_false_ops)
            current_false_ops = [strcmp_op, if_op, scf.YieldOp()]

        main_chain_ops = current_false_ops[:-1]
        ret_op = func.ReturnOp(errmsg_alloc, errflg_alloc)

        new_block.add_ops(
            [
                errmsg_alloc,
                errflg_alloc,
                err_const,
                store_errflg,
                trim_suite_name,
                *main_chain_ops,
                ret_op,
            ]
        )

        body = Region()
        body.add_block(new_block)

        fn_type = builtin.FunctionType.from_lists(
            [suite_name_type, allocatable_type],
            [errmsg_type, errflg_type],
        )
        suite_part_list_fn = func.FuncOp(
            "ccpp_physics_suite_part_list", fn_type, body, visibility="public"
        )
        return suite_part_list_fn, part_global_ops

    def _generate_ccpp_cap_module(self, suite_descriptions, meta_data, public_fns,
                                   ddt_source_module=None, protected_std_names=None,
                                   host_std_names=None, ccpp_mod=None):
        """Build a single combined CCPP cap ModuleOp for all suites.

        Generates one module whose lifecycle subroutines use nested if/else chains
        to dispatch to the appropriate suite cap subroutine.
        """
        all_suite_names = list(suite_descriptions.keys())

        camel_name = (
            self.host_name
            if self.host_name
            else self._derive_camel_case_name(all_suite_names[0])
        )

        # Module name uses the same CamelCase prefix as the subroutine names
        # so that 'module HelloWorld_ccpp_cap' matches 'use HelloWorld_ccpp_cap'
        # in host model files.  --host-name can still override when needed.
        mod_name = camel_name + "_ccpp_cap"

        char_base = TypeConversions.getBaseType("character")
        int_base = TypeConversions.getBaseType("integer")
        suite_name_type = memref.MemRefType(char_base, [DYNAMIC_INDEX])
        errmsg_type = memref.MemRefType(char_base, [512])
        errflg_type = memref.MemRefType(int_base, [])

        common = dict(
            suite_name_type=suite_name_type,
            errmsg_type=errmsg_type,
            errflg_type=errflg_type,
            char_base=char_base,
            int_base=int_base,
            public_fns=public_fns,
        )

        lifecycle_specs = [
            ("_ccpp_physics_initialize", "_init", "_suite_initialize", None),
            ("_ccpp_physics_finalize", "_finalize", "_suite_finalize", None),
            ("_ccpp_physics_timestep_initial", None, "_suite_timestep_initial", None),
            ("_ccpp_physics_timestep_final", None, "_suite_timestep_final", None),
            ("_ccpp_physics_run", None, "_suite_physics", "physics"),
        ]

        all_globals: list = []
        all_definitions: list = []
        all_declarations: list = []

        for fn_suffix, table_postfix, callee_suffix, suite_part in lifecycle_specs:
            if suite_part is not None:
                # Run function: collect per-suite run entries
                suite_run_entries = []
                for suite_name, suite_desc in suite_descriptions.items():
                    suite_callee = suite_name + callee_suffix
                    if suite_callee not in public_fns:
                        continue
                    scheme_names = [
                        scheme.attributes["name"]
                        for group in suite_desc
                        for scheme in group
                    ]
                    suite_run_entries.append(
                        (suite_name, suite_part, suite_callee, scheme_names)
                    )

                if not suite_run_entries:
                    continue

                cap_fn, decls, host_global_ops = self._generate_run_fn(
                    fn_name=camel_name + fn_suffix,
                    suite_run_entries=suite_run_entries,
                    meta_data=meta_data,
                    **common,
                )
                all_globals.extend(host_global_ops)
                all_declarations.extend(decls)
            else:
                # Lifecycle function: collect per-suite callee info
                suite_entries = []
                for suite_name, suite_desc in suite_descriptions.items():
                    suite_callee = suite_name + callee_suffix
                    if suite_callee not in public_fns:
                        continue
                    scheme_names = [
                        scheme.attributes["name"]
                        for group in suite_desc
                        for scheme in group
                    ]
                    if table_postfix is not None:
                        call_ret_types = self._get_suite_lifecycle_return_types(
                            scheme_names, meta_data, table_postfix
                        )
                    else:
                        _, call_ret_types, _, _ = public_fns[suite_callee]
                    suite_entries.append((suite_name, suite_callee, call_ret_types))

                if not suite_entries:
                    continue

                cap_fn, decls = self._generate_lifecycle_fn(
                    fn_name=camel_name + fn_suffix,
                    suite_entries=suite_entries,
                    **common,
                )
                all_declarations.extend(decls)

            all_definitions.append(cap_fn)

        # Generate ccpp_physics_suite_list listing ALL suite names.
        inner_char_type = memref.MemRefType(i8, [DYNAMIC_INDEX])
        allocatable_type = memref.MemRefType(inner_char_type, [])
        suite_list_block = Block(arg_types=[allocatable_type])
        suite_list_block.args[0].name_hint = "suites"

        body_ops = []
        for sn in all_suite_names:
            str_global_name = f"str_{sn}"
            str_len = len(sn)
            arr_type = llvm.LLVMArrayType.from_size_and_type(str_len, i8)

            all_globals.append(
                llvm.GlobalOp(
                    arr_type,
                    str_global_name,
                    "internal",
                    constant=True,
                    value=StringAttr(sn),
                )
            )

            str_len_const = arith.ConstantOp(
                IntegerAttr(str_len, IndexType()), IndexType()
            )
            str_alloc = memref.AllocOp([str_len_const.result], [], inner_char_type)
            addr_op = llvm.AddressOfOp(str_global_name, llvm.LLVMPointerType())
            load_op = llvm.LoadOp(addr_op, arr_type)
            set_str_op = SetStringOp(str_alloc.memref, load_op.dereferenced_value)
            store_ref_op = memref.StoreOp.get(
                str_alloc.memref, suite_list_block.args[0], []
            )
            body_ops.extend(
                [str_len_const, str_alloc, addr_op, load_op, set_str_op, store_ref_op]
            )

        suite_list_block.add_ops([*body_ops, func.ReturnOp()])
        suite_list_region = Region()
        suite_list_region.add_block(suite_list_block)
        suite_list_fn = func.FuncOp(
            "ccpp_physics_suite_list",
            builtin.FunctionType.from_lists([allocatable_type], []),
            suite_list_region,
            visibility="public",
        )
        all_definitions.append(suite_list_fn)

        # Generate ccpp_physics_suite_part_list for all suites.
        part_names = list(
            dict.fromkeys(sp for _, _, _, sp in lifecycle_specs if sp is not None)
        )
        suite_part_entries = [(sn, part_names) for sn in all_suite_names]

        suite_part_list_fn, part_global_ops = self._generate_suite_part_list_fn(
            suite_part_entries=suite_part_entries,
            inner_char_type=inner_char_type,
            allocatable_type=allocatable_type,
            suite_name_type=suite_name_type,
            errmsg_type=errmsg_type,
            errflg_type=errflg_type,
            char_base=char_base,
            int_base=int_base,
        )
        all_globals.extend(part_global_ops)
        all_definitions.append(suite_part_list_fn)
        suite_vars_op = self._build_suite_variables_fn(
            suite_descriptions, ccpp_mod,
            host_std_names or set(),
            protected_std_names or set(),
        )
        all_definitions.append(suite_vars_op)

        # Emit USE-association stubs for DDT types used in any scheme across all suites.
        if ddt_source_module:
            primitive_types = {"real", "integer", "character", "logical", "complex"}
            seen_type_imports: set[str] = set()
            for props in meta_data.values():
                for arg_table in props.arg_tables.values():
                    for arg in arg_table.getFunctionArguments():
                        if not arg.hasAttr("type"):
                            continue
                        arg_type = arg.getAttr("type")
                        if arg_type in primitive_types or arg_type in seen_type_imports:
                            continue
                        mod = ddt_source_module.get(arg_type)
                        if mod is None:
                            continue
                        seen_type_imports.add(arg_type)
                        stub = llvm.GlobalOp(
                            llvm.LLVMArrayType.from_size_and_type(0, i8),
                            arg_type,
                            "internal",
                        )
                        stub.attributes["module"] = StringAttr(mod)
                        all_globals.append(stub)

        module_ops = all_globals + all_definitions + all_declarations

        return builtin.ModuleOp(
            module_ops,
            sym_name=builtin.StringAttr(mod_name),
        )

    def apply(self, ctx: Context, op: builtin.ModuleOp) -> None:
        ccpp_mod = self.find_ccpp_module(op.body.block.ops)
        assert ccpp_mod is not None

        # Build Python descriptor objects from the CCPP metadata IR
        bmdd = BuildMetaDataDescriptions()
        bmdd.traverse(ccpp_mod)
        meta_data_descriptions = bmdd.meta_data

        # Build the suite hierarchy descriptors
        bsd = BuildSchemeDescription()
        bsd.traverse(ccpp_mod)
        suite_descriptions = bsd.schemes

        # Collect public functions from suite cap modules already in the IR
        public_fns = self._collect_public_suite_functions(op.body.block.ops)

        # Build DDT-type-name → Fortran-module-name map (same as suite_cap.py)
        ddt_source_module: dict[str, str] = {}
        for tbl_op in ccpp_mod.body.ops:
            if not isa(tbl_op, ccpp.TablePropertiesOp):
                continue
            if tbl_op.table_type.data != "ddt":
                continue
            src = tbl_op.attributes.get("source_module")
            if src is not None:
                ddt_source_module[tbl_op.table_name.data] = src.data

        # Build set of ALL standard_names provided by the host model (from
        # non-scheme tables in the IR).  Used in _build_suite_variables_fn to
        # exclude scheme-internal args that have no host counterpart.
        host_std_names: set[str] = set()
        for tbl_op in ccpp_mod.body.ops:
            if not isa(tbl_op, ccpp.TablePropertiesOp):
                continue
            if tbl_op.table_type.data == "scheme":
                continue
            for arg_table_op in tbl_op.body.ops:
                if not isa(arg_table_op, ccpp.ArgumentTableOp):
                    continue
                for arg_op in arg_table_op.body.ops:
                    if not isa(arg_op, ccpp.ArgumentOp):
                        continue
                    if arg_op.standard_name is not None:
                        host_std_names.add(arg_op.standard_name.data.lower())

        # Build set of protected host-variable standard_names.
        # Protected variables (e.g. vertical_layer_dimension, horizontal_dimension)
        # are framework-managed and excluded from ccpp_physics_suite_variables lists.
        protected_std_names: set[str] = set()
        for tbl_op in ccpp_mod.body.ops:
            if not isa(tbl_op, ccpp.TablePropertiesOp):
                continue
            if tbl_op.table_type.data not in ("module", "host", "ddt"):
                continue
            for arg_table_op in tbl_op.body.ops:
                if not isa(arg_table_op, ccpp.ArgumentTableOp):
                    continue
                for arg_op in arg_table_op.body.ops:
                    if not isa(arg_op, ccpp.ArgumentOp):
                        continue
                    if (arg_op.properties.get("protected") is not None
                            and arg_op.standard_name is not None):
                        protected_std_names.add(
                            arg_op.standard_name.data.lower()
                        )

        # Generate ONE combined CCPP cap module for all suites
        cap_mod = self._generate_ccpp_cap_module(
            suite_descriptions, meta_data_descriptions, public_fns,
            ddt_source_module=ddt_source_module,
            protected_std_names=protected_std_names,
            host_std_names=host_std_names,
            ccpp_mod=ccpp_mod,
        )
        op.body.block.add_op(cap_mod)
