from dataclasses import dataclass

from xdsl.context import Context
from xdsl.dialects import arith, builtin, func, llvm, memref, scf
from xdsl.dialects.builtin import DYNAMIC_INDEX, IndexType, IntegerAttr, StringAttr, i8
from xdsl.ir import Block, Region
from xdsl.passes import ModulePass
from xdsl.utils.hints import isa

from xdsl_ccpp.dialects import ccpp
from xdsl_ccpp.dialects.ccpp_utils import (
    ArraySectionOp,
    CapVarRefOp,
    HostVarRefOp,
    ModuleVarOp,
    SetStringOp,
    StrCmpOp,
    SuiteVariablesOp,
    TrimOp,
    WriteErrMsgOp,
)
from xdsl_ccpp.transforms.util.ccpp_descriptors import (
    BuildMetaDataDescriptions,
    BuildSchemeDescription,
    CCPPType,
    collect_ddt_source_modules,
)
from xdsl_ccpp.transforms.util.typing import TypeConversions
from xdsl_ccpp.util.ccpp_conventions import (
    CCPP_ERROR_CODE,
    CCPP_ERROR_MESSAGE,
    CCPP_ERROR_STD_NAMES,
    CCPP_FRAMEWORK_STD_NAMES,
    CCPP_HORIZ_DIM_STD_NAME,
    CCPP_LOOP_BEGIN_STD_NAME,
    CCPP_LOOP_END_STD_NAME,
)


@dataclass(frozen=True)
class CCPPCAP(ModulePass):
    """MLIR pass that generates a single combined CCPP physics cap dispatcher module.

    Runs after generate-suite-cap.  For all suites found in the ccpp module,
    generates a single named ModuleOp containing lifecycle dispatcher subroutines
    that use nested if/else chains on ``suite_name`` to dispatch to the appropriate
    suite cap subroutine (generated by generate-suite-cap).

    Output is one ModuleOp (e.g. ``test_host_ccpp_cap``) inserted into the
    top-level module alongside the suite cap modules.
    """

    name = "generate-ccpp-cap"

    # Optional override for the CamelCase host name prefix applied to all
    # generated lifecycle subroutines.  When absent, the prefix is derived
    # automatically from the first suite name (e.g. hello_world_suite → HelloWorld).
    host_name: str = ""

    def find_ccpp_module(self, ops):
        """Return the named 'ccpp' ModuleOp from the given op list, or None."""
        for op in ops:
            if (
                isa(op, builtin.ModuleOp)
                and op.sym_name is not None
                and op.sym_name.data == "ccpp"
            ):
                return op
        return None

    def _collect_public_suite_functions(self, ops):
        """Scan all named ModuleOps in ops and return a map of public function info.

        Returns:
            dict mapping function_name → (module_name, output_types,
            input_types, input_names).
        """
        public_fns = {}
        for op in ops:
            if not (isa(op, builtin.ModuleOp) and op.sym_name is not None):
                continue
            mod_name = op.sym_name.data
            for child in op.body.block.ops:
                if (
                    isa(child, func.FuncOp)
                    and not child.is_declaration
                    and child.sym_visibility is not None
                    and child.sym_visibility.data == "public"
                ):
                    public_fns[child.sym_name.data] = (
                        mod_name,
                        list(child.function_type.outputs),
                        list(child.function_type.inputs),
                        [arg.name_hint for arg in child.body.block.args],
                    )
        return public_fns

    def _derive_camel_case_name(self, suite_name: str) -> str:
        """Convert a snake_case suite name to CamelCase, stripping any '_suite' suffix."""
        name = suite_name
        if name.endswith("_suite"):
            name = name[:-6]
        return "".join(word.capitalize() for word in name.split("_"))

    def _build_suite_variables_fn(self, suite_descriptions, ccpp_mod,
                                   host_std_names, protected_std_names) -> "SuiteVariablesOp":
        """Build the ccpp_physics_suite_variables subroutine for all suites.

        Scans the MLIR IR directly (ArgumentOp properties) rather than going
        through the descriptor layer, avoiding subtle descriptor-build issues.

        Filtering rules (applied per ArgumentOp):
        - Skip if is_interstitial is set (scheme-internal variable)
        - Skip if standard_name is in _CCPP_INTERNAL (framework scalars)
        - Skip if standard_name is in protected_std_names (dimension params)
        - ccpp_error_code/ccpp_error_message always go to output-only
        - Skip if standard_name not in host_std_names (no host counterpart)
        - Arrays (dimensions > 0) go to both input and output
        - Scalars go to input/output/both by declared intent
        - Union across all entry points (_init, _run, _finalize, etc.)
        """
        _CCPP_ERR = CCPP_ERROR_STD_NAMES
        _INTERNAL = CCPP_FRAMEWORK_STD_NAMES
        CM = 36  # character length matching cm=36 in test driver

        suite_vars: dict = {}
        for suite_name, suite_desc in suite_descriptions.items():
            # Collect the set of scheme names belonging to this suite
            scheme_names: set = set()
            for group in suite_desc:
                for scheme in group:
                    scheme_names.add(scheme.attributes["name"])

            input_vars: set = set()
            output_vars: set = set()

            # Scan scheme TablePropertiesOp nodes in the IR directly
            for tbl_op in ccpp_mod.body.ops:
                if not isa(tbl_op, ccpp.TablePropertiesOp):
                    continue
                if tbl_op.table_type.data != "scheme":
                    continue
                if tbl_op.table_name.data not in scheme_names:
                    continue

                # Iterate all entry-point arg tables (_init, _run, _finalize …)
                for arg_table_op in tbl_op.body.ops:
                    if not isa(arg_table_op, ccpp.ArgumentTableOp):
                        continue

                    for arg_op in arg_table_op.body.ops:
                        if not isa(arg_op, ccpp.ArgumentOp):
                            continue

                        # Read all properties directly from the dict to avoid
                        # any issues with xDSL's formal property accessor layer.
                        sn_prop = arg_op.properties.get("standard_name")
                        if sn_prop is None:
                            continue
                        std_name = sn_prop.data.lower()

                        # is_interstitial: UnitAttr when set, None when absent
                        is_int = arg_op.properties.get("is_interstitial")
                        if is_int is not None:
                            continue
                        if std_name in _INTERNAL:
                            continue
                        if std_name in protected_std_names:
                            continue

                        # Error flags → output-only special case
                        if std_name in _CCPP_ERR:
                            output_vars.add(std_name)
                            continue

                        # Exclude args with no matching host variable
                        if std_name not in host_std_names:
                            continue

                        # intent: StringAttr when set
                        intent_prop = arg_op.properties.get("intent")
                        intent = intent_prop.data.lower() if intent_prop is not None else None

                        # dimensions: IntAttr (0 = scalar, absent = scalar)
                        dims_prop = arg_op.properties.get("dimensions")
                        has_dims = (
                            dims_prop is not None and dims_prop.data > 0
                        )

                        if has_dims:
                            # Arrays are always pass-by-reference in Fortran
                            input_vars.add(std_name)
                            output_vars.add(std_name)
                        else:
                            if intent in ("in", "inout"):
                                input_vars.add(std_name)
                            if intent in ("out", "inout"):
                                output_vars.add(std_name)

            required_vars = input_vars | output_vars
            suite_vars[suite_name] = (
                sorted(input_vars),
                sorted(output_vars),
                sorted(required_vars),
            )

        # Build the complete Fortran subroutine as a Python string
        lines: list[str] = []
        lines.append(
            "subroutine ccpp_physics_suite_variables"
            "(suite_name, var_list, errmsg, errflg, input_vars, output_vars)"
        )
        lines.append("  character(len=*), intent(in) :: suite_name")
        lines.append("  character(len=*), allocatable, intent(out) :: var_list(:)")
        lines.append("  character(len=512), intent(out) :: errmsg")
        lines.append("  integer, intent(out) :: errflg")
        lines.append("  logical, optional, intent(in) :: input_vars")
        lines.append("  logical, optional, intent(in) :: output_vars")
        lines.append("  logical :: do_input, do_output")
        lines.append("  errmsg = ''")
        lines.append("  errflg = 0")
        lines.append("  do_input = .true.")
        lines.append("  do_output = .true.")
        lines.append("  if (present(input_vars)) do_input = input_vars")
        lines.append("  if (present(output_vars)) do_output = output_vars")

        for idx, (suite_name, (in_v, out_v, req_v)) in enumerate(suite_vars.items()):
            kw = "if" if idx == 0 else "else if"
            lines.append(f"  {kw} (trim(suite_name) .eq. '{suite_name}') then")
            for branch_name, var_list in (
                ("input only",  "do_input .and. .not. do_output"),
                ("output only", ".not. do_input .and. do_output"),
                ("required",    None),
            ):
                if branch_name == "input only":
                    lines.append(f"    if ({var_list}) then")
                    vlist = in_v
                elif branch_name == "output only":
                    lines.append(f"    else if ({var_list}) then")
                    vlist = out_v
                else:
                    lines.append("    else")
                    vlist = req_v
                lines.append(f"      allocate(var_list({len(vlist)}))")
                for j, v in enumerate(vlist):
                    lines.append(f"      var_list({j + 1}) = '{v:<{CM}}'")
            lines.append("    end if")

        lines.append("  else")
        lines.append(
            '    write(errmsg, \'(3a)\') "No suite named ", trim(suite_name), " found"'
        )
        lines.append("    errflg = 1")
        lines.append("  end if")
        lines.append("end subroutine ccpp_physics_suite_variables")

        return SuiteVariablesOp("\n".join(lines))

    def _build_host_var_map(self, meta_data, include_host: bool = True) -> dict:
        """Build a standard_name → (var_name, table_name) map from host metadata.

        Args:
            meta_data:    descriptor dict from BuildMetaDataDescriptions.
            include_host: when True (default) includes both MODULE and HOST type
                          tables.  When False, only MODULE type tables are scanned.
                          HOST-type variables are ephemeral values passed directly
                          by the host caller; MODULE-type variables are accessible
                          via USE statements.

        Returns:
            dict mapping lowercase standard_name → (local_var_name, table_name).
        """
        table_types = (
            (CCPPType.MODULE, CCPPType.HOST) if include_host else (CCPPType.MODULE,)
        )
        result: dict = {}
        for tbl_name, props in meta_data.items():
            if props.getAttr("type") not in table_types:
                continue
            if tbl_name not in props.arg_tables:
                continue
            for var in props.getArgTable(tbl_name).getFunctionArguments():
                if var.hasAttr("standard_name"):
                    result[var.getAttr("standard_name").lower()] = (var.name, tbl_name)
        return result

    @staticmethod
    def _resolve_member_subscripts(member_name: str, host_var_map: dict) -> tuple:
        """Resolve standard_name tokens in a DDT member subscript to local var names.

        For 'q(:,:,index_of_water_vapor_specific_humidity)' with a host_var_map that
        maps the standard_name to ('index_qv', 'test_host_mod'), returns
        ('q(:,:,index_qv)', [('index_qv', 'test_host_mod')]).

        Bare colons and integer literals are passed through unchanged.
        """
        paren = member_name.find("(")
        if paren < 0:
            return member_name, []
        base = member_name[:paren]
        subscript = member_name[paren + 1: member_name.rfind(")")]
        resolved_tokens = []
        sub_vars = []
        for token in subscript.split(","):
            t = token.strip()
            if t == ":" or t.isdigit():
                resolved_tokens.append(t)
            else:
                t_lower = t.lower()
                if t_lower in host_var_map:
                    local_name, module_name = host_var_map[t_lower]
                    resolved_tokens.append(local_name)
                    sub_vars.append((local_name, module_name))
                else:
                    resolved_tokens.append(t)
        return f"{base}({', '.join(resolved_tokens)})", sub_vars

    def _get_suite_lifecycle_return_types(self, scheme_names, meta_data, table_postfix):
        """Derive the ordered return types of a suite lifecycle subroutine."""
        return [t for t, _n, _s in
                self._get_suite_lifecycle_ret_info(scheme_names, meta_data, table_postfix)]

    def _get_suite_lifecycle_ret_info(self, scheme_names, meta_data, table_postfix):
        """Return [(mlir_type, arg_name, standard_name)] for intent=out scalar args.

        Applies the same filters as suite_cap.py's ``output_arg_list`` so the
        returned types match the actual FuncOp return signature generated by the
        suite cap:
        - intent=out only
        - Scalar (dimensions = 0 or absent) — array outs are block args, not returns
        - Not allocatable — those become __alloc block args
        - Not interstitial — framework-managed vars are not suite cap outputs
        """
        all_out_args = {}
        for scheme_name in scheme_names:
            table_name = scheme_name + table_postfix
            if scheme_name not in meta_data:
                continue
            if table_name not in meta_data[scheme_name].arg_tables:
                continue
            arg_table = meta_data[scheme_name].getArgTable(table_name)
            for fn_arg in arg_table.getFunctionArguments():
                has_dims = fn_arg.hasAttr("dimensions") and fn_arg.getAttr("dimensions") > 0
                # Mirror suite_cap.py's _is_framework_managed logic:
                # interstitials of any type (real, integer, DDT) are excluded —
                # they are stored at suite cap module scope, not returned to caller.
                is_framework_managed = fn_arg.hasAttr("is_interstitial")
                if (
                    fn_arg.getAttr("intent") == "out"
                    and fn_arg.name not in all_out_args
                    and not has_dims
                    and not fn_arg.hasAttr("allocatable")
                    and not is_framework_managed
                ):
                    all_out_args[fn_arg.name] = fn_arg

        result = []
        for arg in all_out_args.values():
            mlir_type = TypeConversions.convert(
                arg.getAttr("type"),
                arg.getAttr("kind") if arg.hasAttr("kind") else None,
                0,
            )
            raw = arg.getAttr("standard_name") if arg.hasAttr("standard_name") else None
            std_name = raw.lower() if raw else None
            result.append((mlir_type, arg.name, std_name))
        return result

    def _generate_lifecycle_fn(
        self,
        fn_name,
        suite_entries,
        suite_name_type,
        errmsg_type,
        errflg_type,
        char_base,
        int_base,
        public_fns,
        meta_data,
        seen_host_globals=None,
        cap_var_map=None,
        host_var_map_lc=None,
        **kwargs,
    ):
        """Build one combined CCPP cap lifecycle FuncOp dispatching over all suites.

        ``suite_entries`` is a list of
        ``(suite_name, suite_callee, call_ret_types, scheme_names, entry_postfix)``
        tuples.

        For lifecycle functions that have no host inputs (timestep_initial/final),
        ``entry_postfix`` is None and the call passes no input arguments.

        For initialize/finalize, ``entry_postfix`` is ``"_init"`` / ``"_finalize"``.
        The callee's input args are looked up in the scheme entry-point metadata and
        resolved against host module variables, mirroring what ``_generate_run_fn``
        does for the physics call.

        Returns ``(FuncOp, [external_decl_FuncOp, ...], [host_GlobalOp, ...])``.
        """
        for suite_name, suite_callee, _ret, _sn, _ep, _ri in suite_entries:
            assert suite_callee in public_fns, (
                f"Suite callee '{suite_callee}' not found among public suite cap "
                f"functions; available: {sorted(public_fns)}"
            )

        # MODULE only: lifecycle input arg lookups use USE statements, which only
        # work for MODULE-type tables.  HOST-type tables are caller-provided args
        # (not Fortran modules) so they must not generate USE stubs.
        host_var_map = self._build_host_var_map(meta_data, include_host=False)

        ccpp_info_type = kwargs.get("ccpp_info_type")
        ccpp_info_module = kwargs.get("ccpp_info_module")

        if ccpp_info_type is not None:
            # ccpp_info_t pattern: single inout arg bundles errmsg/errflg.
            # Use HostVarRefOps (member access) in place of AllocaOps so the
            # printer emits ccpp_info%errmsg / ccpp_info%errflg everywhere.
            new_block = Block(arg_types=[suite_name_type, ccpp_info_type])
            new_block.args[0].name_hint = "suite_name"
            new_block.args[1].name_hint = "ccpp_info"
            errmsg_alloc = HostVarRefOp(
                "ccpp_info", ccpp_info_module, errmsg_type, member_name="errmsg"
            )
            errflg_alloc = HostVarRefOp(
                "ccpp_info", ccpp_info_module, errflg_type, member_name="errflg"
            )
        else:
            # capgen pattern: function returns errmsg/errflg as separate outputs.
            errmsg_alloc = memref.AllocaOp.get(char_base, shape=[512])
            errmsg_alloc.memref.name_hint = "errmsg"
            errflg_alloc = memref.AllocaOp.get(int_base, shape=[])
            errflg_alloc.memref.name_hint = "errflg"
            new_block = Block(arg_types=[suite_name_type])
            new_block.args[0].name_hint = "suite_name"

        err_const = arith.ConstantOp.from_int_and_width(0, 32)
        store_errflg = memref.StoreOp.get(err_const, errflg_alloc, [])
        trim_suite_name = TrimOp(new_block.args[0])

        # Innermost else: no suite matched
        write_err = WriteErrMsgOp(
            errmsg_alloc, trim_suite_name.res, "No suite named ", "found"
        )
        one_err = arith.ConstantOp.from_int_and_width(1, 32)
        store_errflg_err = memref.StoreOp.get(one_err, errflg_alloc, [])
        current_false_ops = [write_err, one_err, store_errflg_err, scf.YieldOp()]

        all_host_global_ops: list = []
        # Use the shared set if provided to avoid duplicate GlobalOps across calls
        if seen_host_globals is None:
            seen_host_globals = set()
        decls = []
        # Placeholder allocas for unmatched args must be declared at function scope,
        # not inside IfOp branches. Collect them here and hoist to the main block.
        hoisted_alloc_ops: list = []

        _cap_var_map = cap_var_map or {}
        _host_var_map_lc = host_var_map_lc or {}

        for suite_name, suite_callee, call_ret_types, scheme_names, entry_postfix, ret_info \
                in reversed(suite_entries):
            _, _, callee_input_types, callee_input_names = public_fns[suite_callee]

            # Build {bare_arg_name → standard_name} from the scheme entry-point tables
            std_name_of: dict = {}
            if entry_postfix is not None:
                for scheme_name in scheme_names:
                    entry_name = scheme_name + entry_postfix
                    if scheme_name not in meta_data:
                        continue
                    if entry_name not in meta_data[scheme_name].arg_tables:
                        continue
                    for fn_arg in (
                        meta_data[scheme_name]
                        .getArgTable(entry_name)
                        .getFunctionArguments()
                    ):
                        # Strip __alloc suffix used for allocatable arg name_hints
                        bare = fn_arg.name.replace("__alloc", "")
                        if bare not in std_name_of and fn_arg.hasAttr("standard_name"):
                            std_name_of[bare] = fn_arg.getAttr("standard_name").lower()

            # Resolve each input arg: host-mapped → HostVarRefOp, other → alloca
            true_branch_pre_ops: list = []
            call_inputs: list = []

            for arg_name, arg_type in zip(callee_input_names, callee_input_types):
                bare = arg_name.replace("__alloc", "")
                std_name = std_name_of.get(bare)

                if std_name and std_name in host_var_map:
                    host_var_name, host_module_name = host_var_map[std_name]
                    ref_op = HostVarRefOp(host_var_name, host_module_name, arg_type)
                    true_branch_pre_ops.append(ref_op)
                    call_inputs.append(ref_op.res)
                    # Emit host global stub for USE statement generation
                    key = (host_var_name, host_module_name)
                    if key not in seen_host_globals:
                        seen_host_globals.add(key)
                        glob = llvm.GlobalOp(
                            llvm.LLVMArrayType.from_size_and_type(1, i8),
                            host_var_name,
                            "external",
                        )
                        glob.attributes["module"] = StringAttr(host_module_name)
                        all_host_global_ops.append(glob)
                elif (
                    ccpp_info_type is not None
                    and std_name == "host_standard_ccpp_type"
                ):
                    # The ccpp_info_t block arg IS the CCPP framework handle — pass
                    # it directly to callees that expect host_standard_ccpp_type.
                    call_inputs.append(new_block.args[1])
                else:
                    # Not host-matched (e.g. optional arg or allocatable DDT arg).
                    # Hoist the alloca to function scope so Fortran can declare it
                    # at the top of the subroutine (not inside an IfOp branch).
                    elem_type = arg_type.element_type
                    shape = list(arg_type.shape.data)
                    n_dyn = sum(1 for d in shape if d.data == DYNAMIC_INDEX)
                    if n_dyn > 0:
                        # Dynamic-dim alloca requires size operands per MLIR rules.
                        # Use zero index constants as placeholders — these are
                        # allocatable args whose storage is managed by the callee.
                        zero_idx = arith.ConstantOp(
                            IntegerAttr(0, IndexType()), IndexType()
                        )
                        alloc_op = memref.AllocaOp.get(
                            elem_type, shape=shape,
                            dynamic_sizes=[zero_idx.result] * n_dyn,
                        )
                        alloc_op.memref.name_hint = f"lc_{bare}__alloc"
                        hoisted_alloc_ops.append(zero_idx)
                        # Ensure the DDT type's module appears in the USE list.
                        from xdsl_ccpp.dialects.ccpp_utils import DerivedType as _DT
                        _CCPP_DDT_MODS = {
                            "ccpp_constituent_properties_t": "ccpp_constituent_prop_mod",
                        }
                        if isinstance(elem_type, _DT):
                            _ddt_mod = _CCPP_DDT_MODS.get(elem_type.type_name.data)
                            if _ddt_mod:
                                _key = (elem_type.type_name.data, _ddt_mod)
                                if _key not in seen_host_globals:
                                    seen_host_globals.add(_key)
                                    _g = llvm.GlobalOp(
                                        llvm.LLVMArrayType.from_size_and_type(1, i8),
                                        elem_type.type_name.data,
                                        "external",
                                    )
                                    _g.attributes["module"] = StringAttr(_ddt_mod)
                                    all_host_global_ops.append(_g)
                    else:
                        alloc_op = memref.AllocaOp.get(elem_type, shape=shape)
                        alloc_op.memref.name_hint = f"lc_{bare}"
                    hoisted_alloc_ops.append(alloc_op)
                    call_inputs.append(alloc_op.memref)

            # ── Verify argument count matches callee signature ─────────────────
            if len(call_inputs) != len(callee_input_types):
                import sys
                raise ValueError(
                    f"Signature mismatch for '{suite_callee}': "
                    f"generated {len(call_inputs)} input arg(s) but callee expects "
                    f"{len(callee_input_types)}.\n"
                    f"  Callee inputs: {callee_input_names}"
                )

            # Build the call, then handle each return value:
            #   errmsg/errflg  → copy to the function's errmsg/errflg allocas
            #   cap-owned DDT  → copy to the module-level cap variable
            #   host variable  → copy back to the host module variable
            call_op = func.CallOp(suite_callee, call_inputs, call_ret_types)
            copy_ops = []
            copy_pre_ops = []  # CapVarRefOps / HostVarRefOps placed before the call
            for idx, (ret_type, _arg_name, std_name) in enumerate(ret_info):
                result = call_op.results[idx]
                # Match errmsg/errflg by standard_name when available (init/finalize),
                # or fall back to type matching for timestep functions where
                # ret_info has std_name=None (built from call_ret_types only).
                if std_name == CCPP_ERROR_MESSAGE or (
                    std_name is None and ret_type == errmsg_type
                ):
                    copy_ops.append(memref.CopyOp(result, errmsg_alloc))
                elif std_name == CCPP_ERROR_CODE or (
                    std_name is None and ret_type == errflg_type
                ):
                    copy_ops.append(memref.CopyOp(result, errflg_alloc))
                elif std_name and std_name in _cap_var_map:
                    # Cap-owned interstitial: copy to module-level var
                    var_name, var_type, _ftn = _cap_var_map[std_name]
                    cap_ref = CapVarRefOp(var_name, var_type)
                    copy_pre_ops.append(cap_ref)
                    copy_ops.append(memref.CopyOp(result, cap_ref.res))
                elif std_name and std_name in _host_var_map_lc:
                    # Host variable: write result back to host module var
                    hv_name, hv_module = _host_var_map_lc[std_name]
                    hv_ref = HostVarRefOp(hv_name, hv_module, ret_type)
                    copy_pre_ops.append(hv_ref)
                    copy_ops.append(memref.CopyOp(result, hv_ref.res))
                    key = (hv_name, hv_module)
                    if key not in (seen_host_globals or set()):
                        if seen_host_globals is not None:
                            seen_host_globals.add(key)
                        hv_glob = llvm.GlobalOp(
                            llvm.LLVMArrayType.from_size_and_type(1, i8),
                            hv_name, "external",
                        )
                        hv_glob.attributes["module"] = StringAttr(hv_module)
                        all_host_global_ops.append(hv_glob)

            # copy_pre_ops (CapVarRefOp/HostVarRefOp) must come BEFORE the call so
            # the printer registers their results in `variables` before _print_call
            # resolves the return-value destinations.
            strcmp_op = StrCmpOp(trim_suite_name.res, literal=suite_name)
            if_op = scf.IfOp(
                strcmp_op.res,
                [],
                true_branch_pre_ops + copy_pre_ops + [call_op] + copy_ops + [scf.YieldOp()],
                current_false_ops,
            )
            current_false_ops = [strcmp_op, if_op, scf.YieldOp()]

        main_chain_ops = current_false_ops[:-1]

        if ccpp_info_type is not None:
            ret_op = func.ReturnOp(new_block.args[1])  # return ccpp_info as inout
            fn_type = builtin.FunctionType.from_lists(
                [suite_name_type, ccpp_info_type],
                [ccpp_info_type],
            )
        else:
            ret_op = func.ReturnOp(errmsg_alloc, errflg_alloc)
            fn_type = builtin.FunctionType.from_lists(
                [suite_name_type],
                [errmsg_type, errflg_type],
            )

        new_block.add_ops(
            [
                errmsg_alloc,
                errflg_alloc,
                *hoisted_alloc_ops,   # placeholder allocas declared at function scope
                err_const,
                store_errflg,
                trim_suite_name,
                *main_chain_ops,
                ret_op,
            ]
        )

        body = Region()
        body.add_block(new_block)
        cap_fn = func.FuncOp(fn_name, fn_type, body, visibility="public")

        for suite_name, suite_callee, call_ret_types, scheme_names, entry_postfix, _ri \
                in suite_entries:
            callee_module, _, callee_input_types, _ = public_fns[suite_callee]
            decl = func.FuncOp.external(suite_callee, callee_input_types, call_ret_types)
            decl.attributes["module"] = StringAttr(callee_module)
            decls.append(decl)

        return cap_fn, decls, all_host_global_ops

    def _generate_run_fn(
        self,
        fn_name,
        suite_run_entries,
        suite_name_type,
        errmsg_type,
        errflg_type,
        char_base,
        int_base,
        public_fns,
        meta_data,
        cap_var_map=None,
        seen_host_globals=None,
        **kwargs,
    ):
        """Build the combined CCPP cap physics run FuncOp dispatching over all suites.

        ``suite_run_entries`` is a list of
        ``(suite_name, suite_part, suite_callee, scheme_names)`` tuples.

        The generated function signature uses the union of non-host physics args
        across all suites.  A nested if/else chain on ``suite_name`` dispatches to
        the appropriate suite; each matching branch has an inner if/else on
        ``suite_part``.  Host variable references and array sections are placed
        inside each suite's branch.

        Returns ``(FuncOp, [external_decl_FuncOp, ...], host_global_ops)``.
        """
        for _, _, suite_callee, _ in suite_run_entries:
            assert suite_callee in public_fns, (
                f"Suite callee '{suite_callee}' not found; available: {sorted(public_fns)}"
            )

        suite_part_type = suite_name_type

        # ── Build host variable maps from metadata ─────────────────────────────
        # MODULE only: run functions access host vars via USE statements, so only
        # MODULE-type variables are directly referenceable.  HOST-type vars (e.g.
        # loop bounds) are passed as block args by the caller instead.
        host_var_map = self._build_host_var_map(meta_data, include_host=False)

        # host_block_std_names: standard_names in HOST-type tables.
        # These are ephemeral values the host passes directly (e.g. col_start/col_end
        # from protected loop-bound variables).  They correctly become block args and
        # should NOT trigger an "unmatched" warning.
        host_block_std_names: set = set()
        for tbl_name, props in meta_data.items():
            if props.getAttr("type") != CCPPType.HOST:
                continue
            if tbl_name not in props.arg_tables:
                continue
            for var in props.getArgTable(tbl_name).getFunctionArguments():
                if var.hasAttr("standard_name"):
                    host_block_std_names.add(var.getAttr("standard_name").lower())

        # constituent_std_names: standard_names of scheme args with constituent=True.
        # The host provides these as block args (constituent/tendency arrays);
        # they have no host metadata entry and should NOT trigger an "unmatched" warning.
        constituent_std_names: set = set()
        for _mod_name, props in meta_data.items():
            if props.getAttr("type") != CCPPType.SCHEME:
                continue
            for arg_tbl in props.arg_tables.values():
                for var in arg_tbl.getFunctionArguments():
                    if var.hasAttr("constituent") and var.hasAttr("standard_name"):
                        constituent_std_names.add(var.getAttr("standard_name").lower())

        # ddt_instance_map: ddt_type_name → (instance_var_name, module_name)
        # Maps each DDT type name to the MODULE/HOST variable that holds an instance.
        # The set of DDT type names is derived directly from DDT table names — no need
        # to scan DDT member args separately.
        ddt_type_names = {
            tbl_name
            for tbl_name, props in meta_data.items()
            if props.getAttr("type") == CCPPType.DDT
        }
        ddt_instance_map = {}
        for tbl_name, props in meta_data.items():
            if props.getAttr("type") not in (CCPPType.MODULE, CCPPType.HOST):
                continue
            if tbl_name not in props.arg_tables:
                continue
            for var in props.getArgTable(tbl_name).getFunctionArguments():
                if var.hasAttr("type"):
                    var_type = var.getAttr("type")
                    if var_type in ddt_type_names:
                        ddt_instance_map[var_type] = (var.name, tbl_name)

        # ── Per-suite information ──────────────────────────────────────────────
        per_suite = []
        all_host_global_ops: list = []
        # Use the caller-provided seen_host_globals set so GlobalOps are deduplicated
        # across all functions (lifecycle + run) in the same cap module.
        if seen_host_globals is None:
            seen_host_globals = set()

        for suite_name, suite_part, suite_callee, scheme_names in suite_run_entries:
            (
                callee_module,
                callee_output_types,
                callee_input_types,
                callee_input_names,
            ) = public_fns[suite_callee]

            # Build {local_arg_name → standard_name} from the _run arg tables.
            std_name_of = {}
            for scheme_name in scheme_names:
                table_name = scheme_name + "_run"
                if scheme_name not in meta_data:
                    continue
                if table_name not in meta_data[scheme_name].arg_tables:
                    continue
                for fn_arg in (
                    meta_data[scheme_name]
                    .getArgTable(table_name)
                    .getFunctionArguments()
                ):
                    if fn_arg.name not in std_name_of and fn_arg.hasAttr(
                        "standard_name"
                    ):
                        std_name_of[fn_arg.name] = fn_arg.getAttr("standard_name").lower()

            # Also check HOST and MODULE tables for suite-level args (like col_start/
            # col_end) that don't appear directly in any scheme _run table but are
            # part of the suite cap's signature for loop bounds / array sectioning.
            for callee_arg in callee_input_names:
                if callee_arg in std_name_of:
                    continue
                bare = callee_arg.replace("__alloc", "")
                for tbl_name, props in meta_data.items():
                    if props.getAttr("type") not in (CCPPType.HOST, CCPPType.MODULE):
                        continue
                    if tbl_name not in props.arg_tables:
                        continue
                    for var in props.getArgTable(tbl_name).getFunctionArguments():
                        if var.name == bare and var.hasAttr("standard_name"):
                            std_name_of[bare] = var.getAttr("standard_name").lower()
                            break

            # Build local_name → (host_var, host_module, is_ddt) from the match pass
            # results stored in descriptor objects.  HostVariableMatchPass already
            # computed model_var_name / model_module_name for every matched scheme arg
            # and stored them as properties on the IR ops; BuildMetaDataDescriptions
            # copies those into the CCPPArgument descriptors via known_props.
            # Using this avoids re-deriving the same information from raw metadata.
            local_to_host_info: dict = {}
            for scheme_name in scheme_names:
                table_name = scheme_name + "_run"
                if scheme_name not in meta_data:
                    continue
                if table_name not in meta_data[scheme_name].arg_tables:
                    continue
                for fn_arg in (
                    meta_data[scheme_name]
                    .getArgTable(table_name)
                    .getFunctionArguments()
                ):
                    bare_name = fn_arg.name.replace("__alloc", "")
                    if bare_name not in local_to_host_info and fn_arg.hasAttr(
                        "model_var_name"
                    ):
                        local_to_host_info[bare_name] = (
                            fn_arg.getAttr("model_var_name"),
                            fn_arg.getAttr("model_module_name"),
                            fn_arg.hasAttr("model_var_is_ddt"),
                        )

            # Classify each callee input arg using match pass results as primary source.
            physics_arg_sources = []
            for arg_name in callee_input_names:
                bare = arg_name.replace("__alloc", "")
                std_name = std_name_of.get(bare) or std_name_of.get(arg_name)

                if bare in local_to_host_info and not (
                    std_name and std_name in host_block_std_names
                ):
                    # local_to_host_info has a match, AND it is not a protected
                    # HOST-type block arg (those are passed by the caller, not
                    # accessed via a USE statement).
                    host_var, host_mod, is_ddt = local_to_host_info[bare]
                    if is_ddt:
                        # DDT member: model_module_name is the DDT table/type name.
                        # Find the Fortran instance variable via ddt_instance_map.
                        ddt_type_name = host_mod
                        if ddt_type_name in ddt_instance_map:
                            instance_var, instance_module = ddt_instance_map[ddt_type_name]
                            # Skip DDT instances whose instance variable lives in a HOST-type
                            # table (e.g. ccpp_info_t accessed through 'ccpp' in test_host).
                            # HOST-type tables are caller-provided interfaces, not Fortran
                            # modules — their contents become block args, not USE stubs.
                            if (
                                instance_module in meta_data
                                and meta_data[instance_module].getAttr("type") == CCPPType.HOST
                            ):
                                physics_arg_sources.append(("block",))
                            else:
                                physics_arg_sources.append(
                                    ("ddt_member", instance_var, instance_module, host_var)
                                )
                        else:
                            import sys
                            print(
                                f"Warning: '{suite_callee}' arg '{arg_name}' "
                                f"(standard_name='{std_name}') matched DDT type "
                                f"'{ddt_type_name}' but no module-level instance was "
                                f"found — treating as a host-caller block argument.",
                                file=sys.stderr,
                            )
                            physics_arg_sources.append(("block",))
                    else:
                        physics_arg_sources.append(("host", host_var, host_mod))
                elif std_name and cap_var_map and std_name in cap_var_map:
                    # Cap-owned module variable (e.g. vmr interstitial DDT)
                    physics_arg_sources.append(("cap_var", std_name))
                else:
                    if std_name and std_name not in host_block_std_names \
                            and std_name not in CCPP_FRAMEWORK_STD_NAMES \
                            and std_name not in constituent_std_names:
                        import sys
                        print(
                            f"Warning: '{suite_callee}' arg '{arg_name}' "
                            f"(standard_name='{std_name}') has no host variable "
                            f"match — treating as a host-caller block argument. "
                            f"Check that the host metadata provides this variable.",
                            file=sys.stderr,
                        )
                    physics_arg_sources.append(("block",))

            non_host_args = [
                (callee_input_names[i], callee_input_types[i],
                 std_name_of.get(callee_input_names[i].replace("__alloc", ""),
                                 callee_input_names[i]))
                for i, src in enumerate(physics_arg_sources)
                if src[0] == "block"
                # cap_var sources are cap-internal; don't expose as block args
            ]

            # Collect module-level host global stubs (shared across all suites).
            for i, (_arg_name, _arg_type) in enumerate(
                zip(callee_input_names, callee_input_types)
            ):
                src = physics_arg_sources[i]
                if src[0] == "host":
                    _, host_var_name, host_module_name = src
                    stub_name, stub_module = host_var_name, host_module_name
                elif src[0] == "ddt_member":
                    _, instance_var, instance_module, _member = src
                    stub_name, stub_module = instance_var, instance_module
                elif src[0] == "cap_var":
                    continue  # cap vars live in the same module, no USE needed
                else:
                    continue
                key = (stub_name, stub_module)
                if key not in seen_host_globals:
                    seen_host_globals.add(key)
                    glob = llvm.GlobalOp(
                        llvm.LLVMArrayType.from_size_and_type(1, i8),
                        stub_name,
                        "external",
                    )
                    glob.attributes["module"] = StringAttr(stub_module)
                    all_host_global_ops.append(glob)

            per_suite.append(
                {
                    "suite_name": suite_name,
                    "suite_part": suite_part,
                    "suite_callee": suite_callee,
                    "callee_module": callee_module,
                    "callee_output_types": callee_output_types,
                    "callee_input_types": callee_input_types,
                    "callee_input_names": callee_input_names,
                    "physics_arg_sources": physics_arg_sources,
                    "non_host_args": non_host_args,
                    "std_name_of": std_name_of,
                    "scheme_names": scheme_names,
                }
            )

        # ── Union of non-host args across all suites (ordered by first appearance) ──
        # Deduplicate by standard_name: different schemes may use different local
        # names for the same variable (e.g. 'cols'/'cole' vs 'col_start'/'col_end'
        # for horizontal_loop_begin/end).  Only the first-seen local name is kept.
        union_non_host_args: dict = {}  # canonical_arg_name → arg_type
        seen_non_host_std_names: dict = {}  # std_name → canonical_arg_name
        # Also build a rename map for per-suite block_arg_map construction below.
        non_host_std_to_canonical: dict = {}  # suite-level std_name → canonical name
        for info in per_suite:
            for arg_name, arg_type, std_name in info["non_host_args"]:
                if std_name and std_name in seen_non_host_std_names:
                    # Same standard_name seen before — record the rename
                    canonical = seen_non_host_std_names[std_name]
                    non_host_std_to_canonical[std_name] = canonical
                elif arg_name not in union_non_host_args:
                    union_non_host_args[arg_name] = arg_type
                    if std_name:
                        seen_non_host_std_names[std_name] = arg_name
                        non_host_std_to_canonical[std_name] = arg_name

        ccpp_info_type = kwargs.get("ccpp_info_type")
        ccpp_info_module = kwargs.get("ccpp_info_module")

        # When the host uses the ccpp_info_t pattern, loop bounds (col_start/col_end)
        # come from ccpp_info%col_start/col_end — exclude them from the block args.
        if ccpp_info_type is not None:
            # Collect all member names of the ccpp_info_t DDT from meta_data.
            # These are fields provided by ccpp_info, not separate block args.
            _ccpp_ddt_name = ccpp_info_type.element_type.type_name.data
            _ccpp_member_names: set = set()
            _ccpp_member_std_names: set = {CCPP_LOOP_BEGIN_STD_NAME, CCPP_LOOP_END_STD_NAME}
            for _mn, _mp in meta_data.items():
                if _mn != _ccpp_ddt_name:
                    continue
                if _mn not in _mp.arg_tables:
                    continue
                for _mv in _mp.getArgTable(_mn).getFunctionArguments():
                    _ccpp_member_names.add(_mv.name)
                    if _mv.hasAttr("standard_name"):
                        _ccpp_member_std_names.add(_mv.getAttr("standard_name").lower())

            # Also collect canonical arg names for loop-begin/end std_names.
            _ccpp_provided_canonicals = {
                non_host_std_to_canonical[s]
                for s in _ccpp_member_std_names
                if s in non_host_std_to_canonical
            }
            # Filter: remove args whose arg_name matches a ccpp_info member OR
            # whose canonical name maps to a ccpp_info-provided std_name.
            union_non_host_args = {
                k: v for k, v in union_non_host_args.items()
                if k not in _ccpp_member_names and k not in _ccpp_provided_canonicals
            }

        n_non_host = len(union_non_host_args)

        if ccpp_info_type is not None:
            all_block_types = (
                [suite_name_type, suite_part_type, ccpp_info_type]
                + list(union_non_host_args.values())
            )
        else:
            all_block_types = (
                [suite_name_type, suite_part_type]
                + list(union_non_host_args.values())
                + [errmsg_type, errflg_type]
            )
        new_block = Block(arg_types=all_block_types)

        suite_name_arg = new_block.args[0]
        suite_name_arg.name_hint = "suite_name"
        suite_part_arg = new_block.args[1]

        if ccpp_info_type is not None:
            ccpp_info_block_arg = new_block.args[2]
            ccpp_info_block_arg.name_hint = "ccpp_info"
            suite_part_arg.name_hint = "suite_part"

            block_arg_map = {}
            for i, arg_name in enumerate(union_non_host_args):
                ba = new_block.args[3 + i]
                ba.name_hint = arg_name
                block_arg_map[arg_name] = ba

            # Loop bounds from ccpp_info%col_start / col_end
            int_type = memref.MemRefType(int_base, [])
            col_start_ref = HostVarRefOp(
                "ccpp_info", ccpp_info_module, int_type, member_name="col_start"
            )
            col_end_ref = HostVarRefOp(
                "ccpp_info", ccpp_info_module, int_type, member_name="col_end"
            )
            col_begin_key = non_host_std_to_canonical.get(CCPP_LOOP_BEGIN_STD_NAME)
            col_end_key = non_host_std_to_canonical.get(CCPP_LOOP_END_STD_NAME)
            if col_begin_key:
                block_arg_map[col_begin_key] = col_start_ref.res
            if col_end_key:
                block_arg_map[col_end_key] = col_end_ref.res
            # Also map the ccpp_info_t member names directly so callee arg
            # lookup works even when the callee uses member names with no std_name.
            block_arg_map["col_start"] = col_start_ref.res
            block_arg_map["col_end"] = col_end_ref.res

            # errmsg/errflg from ccpp_info members (no separate block args)
            errmsg_alloc = HostVarRefOp(
                "ccpp_info", ccpp_info_module, errmsg_type, member_name="errmsg"
            )
            errflg_alloc = HostVarRefOp(
                "ccpp_info", ccpp_info_module, errflg_type, member_name="errflg"
            )
            errmsg_arg = errmsg_alloc.res
            errflg_arg = errflg_alloc.res
            # Map member names for errmsg/errflg so callee arg lookup works.
            block_arg_map["errmsg"] = errmsg_alloc.res
            block_arg_map["errflg"] = errflg_alloc.res
        else:
            suite_part_arg.name_hint = "suite_part"
            block_arg_map = {}
            for i, arg_name in enumerate(union_non_host_args):
                ba = new_block.args[2 + i]
                ba.name_hint = arg_name
                block_arg_map[arg_name] = ba

            errmsg_arg = new_block.args[2 + n_non_host]
            errmsg_arg.name_hint = "errmsg"
            errflg_arg = new_block.args[2 + n_non_host + 1]
            errflg_arg.name_hint = "errflg"
            col_start_ref = None
            col_end_ref = None
            errmsg_alloc = None
            errflg_alloc = None

        # ── Main block setup ───────────────────────────────────────────────────
        err_const = arith.ConstantOp.from_int_and_width(0, 32)
        store_errflg = memref.StoreOp.get(err_const, errflg_arg, [])

        trim_suite_name = TrimOp(suite_name_arg)

        # Innermost else: no suite matched
        write_suite_name_err = WriteErrMsgOp(
            errmsg_arg, trim_suite_name.res, "No suite named ", "found"
        )
        one_outer_err = arith.ConstantOp.from_int_and_width(1, 32)
        store_outer_err = memref.StoreOp.get(one_outer_err, errflg_arg, [])

        # ── Build nested if/else chain from inside out ─────────────────────────
        current_false_ops = [
            write_suite_name_err,
            one_outer_err,
            store_outer_err,
            scf.YieldOp(),
        ]
        all_decls = []

        # Group per_suite entries by suite_name (preserving first-seen order).
        per_suite_grouped: dict = {}
        for _info in per_suite:
            _sn = _info["suite_name"]
            if _sn not in per_suite_grouped:
                per_suite_grouped[_sn] = []
            per_suite_grouped[_sn].append(_info)

        for suite_name, suite_infos in reversed(list(per_suite_grouped.items())):
            # trim_suite_part is created once and shared across all parts of this suite.
            trim_suite_part = TrimOp(suite_part_arg)

            # Innermost false branch: no suite_part matched.
            write_part_err = WriteErrMsgOp(
                errmsg_arg, trim_suite_part.res,
                "No suite part named ", f" found in suite {suite_name}",
            )
            one_part_err = arith.ConstantOp.from_int_and_width(1, 32)
            store_part_err = memref.StoreOp.get(one_part_err, errflg_arg, [])
            part_inner_false = [write_part_err, one_part_err, store_part_err, scf.YieldOp()]

            for info in reversed(suite_infos):
                suite_part = info["suite_part"]
                suite_callee = info["suite_callee"]
                callee_module = info["callee_module"]
                callee_output_types = info["callee_output_types"]
                callee_input_types = info["callee_input_types"]
                callee_input_names = info["callee_input_names"]
                physics_arg_sources = info["physics_arg_sources"]
                std_name_of = info["std_name_of"]

                # ── HostVarRefOps ─────────────────────────────────────────────
                host_var_ref_ops = []
                host_var_ref_results = {}
                host_name_to_ref_result = {}

                for i, (arg_name, arg_type) in enumerate(
                    zip(callee_input_names, callee_input_types)
                ):
                    src = physics_arg_sources[i]
                    if src[0] == "host":
                        _, host_var_name, host_module_name = src
                        ref_op = HostVarRefOp(host_var_name, host_module_name, arg_type)
                        host_var_ref_ops.append(ref_op)
                        host_var_ref_results[arg_name] = ref_op.res
                        host_name_to_ref_result[host_var_name] = ref_op.res
                    elif src[0] == "ddt_member":
                        _, instance_var, instance_module, member_name = src
                        # Resolve std_name tokens in subscript to local variable names
                        resolved_member, sub_vars = self._resolve_member_subscripts(
                            member_name, host_var_map
                        )
                        ref_op = HostVarRefOp(
                            instance_var, instance_module, arg_type,
                            member_name=resolved_member,
                        )
                        host_var_ref_ops.append(ref_op)
                        host_var_ref_results[arg_name] = ref_op.res
                        host_name_to_ref_result[f"{instance_var}%{resolved_member}"] = ref_op.res
                        # Emit USE stubs for subscript variables (already resolved to local names)
                        for local_name, module_name in sub_vars:
                            key = (local_name, module_name)
                            if key not in seen_host_globals:
                                seen_host_globals.add(key)
                                sv_glob = llvm.GlobalOp(
                                    llvm.LLVMArrayType.from_size_and_type(1, i8),
                                    local_name, "external",
                                )
                                sv_glob.attributes["module"] = StringAttr(module_name)
                                all_host_global_ops.append(sv_glob)
                    elif src[0] == "cap_var":
                        _, std_name_cv = src
                        cv_name, cv_type, _ftn = cap_var_map[std_name_cv]
                        cap_ref = CapVarRefOp(cv_name, arg_type)
                        host_var_ref_ops.append(cap_ref)
                        host_var_ref_results[arg_name] = cap_ref.res

                # ── ArraySectionOps ───────────────────────────────────────────
                array_section_pre_ops = []
                array_section_extra_ops = []
                array_section_main_ops = []
                one_const_for_sections = None

                for i, (arg_name, arg_type) in enumerate(
                    zip(callee_input_names, callee_input_types)
                ):
                    src = physics_arg_sources[i]
                    if src[0] == "host":
                        _, host_var_name, host_module_name = src
                        lookup_var, lookup_mod = host_var_name, host_module_name
                    elif src[0] == "ddt_member":
                        _, instance_var, instance_module, member_name = src
                        lookup_var, lookup_mod = member_name, instance_module
                    else:
                        continue

                    # Look up the var descriptor; for DDT members, search the DDT table
                    host_var_name = lookup_var
                    host_module_name = lookup_mod
                    try:
                        # Try the module table first, then DDT tables
                        if lookup_mod in meta_data and lookup_mod in meta_data[lookup_mod].arg_tables:
                            mod_arg_table = meta_data[lookup_mod].getArgTable(lookup_mod)
                            host_var_desc = mod_arg_table.getFunctionArgument(lookup_var)
                        else:
                            # DDT member: search all DDT tables for the member
                            raise AssertionError("not found in module, try DDT")
                    except (KeyError, AssertionError):
                        # Try DDT tables
                        found = False
                        for tbl_name, props in meta_data.items():
                            if props.getAttr("type") != CCPPType.DDT:
                                continue
                            if tbl_name not in props.arg_tables:
                                continue
                            try:
                                host_var_desc = props.getArgTable(tbl_name).getFunctionArgument(lookup_var)
                                found = True
                                break
                            except (KeyError, AssertionError):
                                continue
                        if not found:
                            continue

                    if not host_var_desc.hasAttr("dim_names"):
                        continue
                    dim_names_list = host_var_desc.getAttr("dim_names")
                    if not dim_names_list or dim_names_list[0].lower() != CCPP_HORIZ_DIM_STD_NAME:
                        continue

                    # Find the canonical block arg names for loop begin/end via
                    # standard_name, since different schemes use different local names.
                    col_begin_key = non_host_std_to_canonical.get(CCPP_LOOP_BEGIN_STD_NAME)
                    col_end_key   = non_host_std_to_canonical.get(CCPP_LOOP_END_STD_NAME)
                    if not col_begin_key or not col_end_key:
                        continue
                    if col_begin_key not in block_arg_map or col_end_key not in block_arg_map:
                        continue

                    lowers = [block_arg_map[col_begin_key]]
                    uppers = [block_arg_map[col_end_key]]

                    valid = True
                    for dim_std_name in dim_names_list[1:]:
                        if dim_std_name not in host_var_map:
                            valid = False
                            break
                        dim_var_name, dim_module_name = host_var_map[dim_std_name]

                        if dim_var_name in host_name_to_ref_result:
                            dim_upper_ref = host_name_to_ref_result[dim_var_name]
                        else:
                            dim_ref_op = HostVarRefOp(
                                dim_var_name,
                                dim_module_name,
                                TypeConversions.getBaseType("integer"),
                            )
                            array_section_extra_ops.append(dim_ref_op)
                            host_name_to_ref_result[dim_var_name] = dim_ref_op.res
                            dim_upper_ref = dim_ref_op.res

                            key = (dim_var_name, dim_module_name)
                            if key not in seen_host_globals:
                                seen_host_globals.add(key)
                                dim_glob = llvm.GlobalOp(
                                    llvm.LLVMArrayType.from_size_and_type(1, i8),
                                    dim_var_name,
                                    "external",
                                )
                                dim_glob.attributes["module"] = StringAttr(dim_module_name)
                                all_host_global_ops.append(dim_glob)

                        if one_const_for_sections is None:
                            one_const_for_sections = arith.ConstantOp.from_int_and_width(
                                1, 32
                            )
                            array_section_pre_ops.append(one_const_for_sections)

                        lowers.append(one_const_for_sections.result)
                        uppers.append(dim_upper_ref)

                    if not valid or len(lowers) < 2:
                        continue

                    section = ArraySectionOp(
                        host_var_ref_results[arg_name],
                        lowers,
                        uppers,
                    )
                    array_section_main_ops.append(section)
                    host_var_ref_results[arg_name] = section.res

                array_section_ops = (
                    array_section_pre_ops + array_section_extra_ops + array_section_main_ops
                )

                # ── Build call args in callee order ───────────────────────────
                call_args = []
                for i, arg_name in enumerate(callee_input_names):
                    src = physics_arg_sources[i]
                    if src[0] in ("host", "ddt_member", "cap_var"):
                        call_args.append(host_var_ref_results[arg_name])
                    else:
                        # Block arg: use canonical name if this arg was deduplicated
                        bare = arg_name.replace("__alloc", "")
                        std = std_name_of.get(bare, bare)
                        canonical = non_host_std_to_canonical.get(std, arg_name)
                        # Fall back to arg_name if canonical not in block_arg_map
                        key = canonical if canonical in block_arg_map else arg_name
                        call_args.append(block_arg_map[key])

                # ── Verify argument count matches callee signature ─────────────
                if len(call_args) != len(callee_input_types):
                    import sys
                    raise ValueError(
                        f"Signature mismatch for '{suite_callee}': "
                        f"generated {len(call_args)} input arg(s) but callee expects "
                        f"{len(callee_input_types)}.\n"
                        f"  Callee inputs:   {callee_input_names}\n"
                        f"  Generated args:  {[str(a) for a in call_args]}"
                    )

                # ── Inner if for suite_part ───────────────────────────────────
                suite_part_eq = StrCmpOp(trim_suite_part.res, literal=suite_part)

                call_op = func.CallOp(suite_callee, call_args, callee_output_types)

                # CapVarRefOps for inout-echo returns must be placed BEFORE the call
                # so the printer can resolve their names when processing return positions.
                cap_var_inout_refs: list = []
                copy_ops = []
                for idx, ret_type in enumerate(callee_output_types):
                    result = call_op.results[idx]
                    if ret_type == errmsg_type:
                        copy_ops.append(memref.CopyOp(result, errmsg_arg))
                    elif ret_type == errflg_type:
                        copy_ops.append(memref.CopyOp(result, errflg_arg))
                    else:
                        # Check for a cap_var input of the same type — this is an inout
                        # echo: the suite cap returns the scalar cap_var after modifying it.
                        # Adding a CopyOp lets the printer resolve the return name so it
                        # can suppress the echo in _print_call.
                        for i, (a_name, a_type) in enumerate(
                            zip(callee_input_names, callee_input_types)
                        ):
                            if a_type == ret_type and physics_arg_sources[i][0] == "cap_var":
                                _, std_name_cv = physics_arg_sources[i]
                                cv_name, cv_type, _ = cap_var_map[std_name_cv]
                                cap_ref = CapVarRefOp(cv_name, a_type)
                                cap_var_inout_refs.append(cap_ref)
                                copy_ops.append(memref.CopyOp(result, cap_ref.res))
                                break

                inner_if_true = cap_var_inout_refs + [call_op] + copy_ops

                inner_if = scf.IfOp(
                    suite_part_eq.res,
                    [],
                    [*host_var_ref_ops, *array_section_ops, *inner_if_true, scf.YieldOp()],
                    part_inner_false,
                )
                part_inner_false = [suite_part_eq, inner_if, scf.YieldOp()]

                decl = func.FuncOp.external(
                    suite_callee, callee_input_types, callee_output_types
                )
                decl.attributes["module"] = StringAttr(callee_module)
                all_decls.append(decl)

            # Outer if for suite_name (after processing all groups)
            true_branch_ops = [trim_suite_part, *part_inner_false[:-1], scf.YieldOp()]
            strcmp_op = StrCmpOp(trim_suite_name.res, literal=suite_name)
            if_op = scf.IfOp(
                strcmp_op.res,
                [],
                true_branch_ops,
                current_false_ops,
            )
            current_false_ops = [strcmp_op, if_op, scf.YieldOp()]

        # Strip trailing YieldOp — main block ends with ReturnOp
        main_chain_ops = current_false_ops[:-1]

        if ccpp_info_type is not None:
            ret_op = func.ReturnOp(ccpp_info_block_arg)  # ccpp_info is inout
            fn_type = builtin.FunctionType.from_lists(
                all_block_types, [ccpp_info_type]
            )
            # Place col_start/col_end/errmsg/errflg HostVarRefOps before dispatch
            preamble_ops = [col_start_ref, col_end_ref, errmsg_alloc, errflg_alloc]
        else:
            ret_op = func.ReturnOp(errmsg_arg, errflg_arg)
            fn_type = builtin.FunctionType.from_lists(
                all_block_types, [errmsg_type, errflg_type]
            )
            preamble_ops = []

        new_block.add_ops(
            [
                *preamble_ops,
                err_const,
                store_errflg,
                trim_suite_name,
                *main_chain_ops,
                ret_op,
            ]
        )

        body = Region()
        body.add_block(new_block)
        cap_fn = func.FuncOp(fn_name, fn_type, body, visibility="public")
        return cap_fn, all_decls, all_host_global_ops

    def _generate_suite_part_list_fn(
        self,
        suite_part_entries,
        inner_char_type,
        allocatable_type,
        suite_name_type,
        errmsg_type,
        errflg_type,
        char_base,
        int_base,
    ):
        """Build the ccpp_physics_suite_part_list FuncOp for all suites.

        ``suite_part_entries`` is a list of ``(suite_name, [part_names])`` tuples.
        Generates a subroutine with a nested if/else chain that checks suite_name
        and fills part_list with the matching suite's part names.

        Returns (FuncOp, list[llvm.GlobalOp]).
        """
        # Collect ALL unique part names for shared global string constants.
        all_part_names = list(
            dict.fromkeys(
                pn for _, part_names in suite_part_entries for pn in part_names
            )
        )

        part_global_ops = []
        part_global_names: dict = {}
        for pn in all_part_names:
            str_global_name = f"str_{pn}"
            arr_type = llvm.LLVMArrayType.from_size_and_type(len(pn), i8)
            part_global_ops.append(
                llvm.GlobalOp(
                    arr_type,
                    str_global_name,
                    "internal",
                    constant=True,
                    value=StringAttr(pn),
                )
            )
            part_global_names[pn] = (str_global_name, arr_type)

        new_block = Block(arg_types=[suite_name_type, allocatable_type])
        new_block.args[0].name_hint = "suite_name"
        new_block.args[1].name_hint = "part_list"

        errmsg_alloc = memref.AllocaOp.get(char_base, shape=[512])
        errmsg_alloc.memref.name_hint = "errmsg"
        errflg_alloc = memref.AllocaOp.get(int_base, shape=[])
        errflg_alloc.memref.name_hint = "errflg"

        err_const = arith.ConstantOp.from_int_and_width(0, 32)
        store_errflg = memref.StoreOp.get(err_const, errflg_alloc, [])

        trim_suite_name = TrimOp(new_block.args[0])

        # Innermost else: no suite matched
        write_err = WriteErrMsgOp(
            errmsg_alloc, trim_suite_name.res, "No suite named ", " found"
        )
        one_err = arith.ConstantOp.from_int_and_width(1, 32)
        store_errflg_err = memref.StoreOp.get(one_err, errflg_alloc, [])

        # Build chain from inside out
        current_false_ops = [write_err, one_err, store_errflg_err, scf.YieldOp()]

        for suite_name, part_names in reversed(suite_part_entries):
            strcmp_op = StrCmpOp(trim_suite_name.res, literal=suite_name)

            true_ops = []
            for pn in part_names:
                str_global_name, arr_type = part_global_names[pn]
                str_len_const = arith.ConstantOp(
                    IntegerAttr(len(pn), IndexType()), IndexType()
                )
                str_alloc = memref.AllocOp([str_len_const.result], [], inner_char_type)
                addr_op = llvm.AddressOfOp(str_global_name, llvm.LLVMPointerType())
                load_op = llvm.LoadOp(addr_op, arr_type)
                set_str_op = SetStringOp(str_alloc.memref, load_op.dereferenced_value)
                store_ref_op = memref.StoreOp.get(
                    str_alloc.memref, new_block.args[1], []
                )
                true_ops.extend(
                    [
                        str_len_const,
                        str_alloc,
                        addr_op,
                        load_op,
                        set_str_op,
                        store_ref_op,
                    ]
                )
            true_ops.append(scf.YieldOp())

            if_op = scf.IfOp(strcmp_op.res, [], true_ops, current_false_ops)
            current_false_ops = [strcmp_op, if_op, scf.YieldOp()]

        main_chain_ops = current_false_ops[:-1]
        ret_op = func.ReturnOp(errmsg_alloc, errflg_alloc)

        new_block.add_ops(
            [
                errmsg_alloc,
                errflg_alloc,
                err_const,
                store_errflg,
                trim_suite_name,
                *main_chain_ops,
                ret_op,
            ]
        )

        body = Region()
        body.add_block(new_block)

        fn_type = builtin.FunctionType.from_lists(
            [suite_name_type, allocatable_type],
            [errmsg_type, errflg_type],
        )
        suite_part_list_fn = func.FuncOp(
            "ccpp_physics_suite_part_list", fn_type, body, visibility="public"
        )
        return suite_part_list_fn, part_global_ops

    def _generate_ccpp_cap_module(self, suite_descriptions, meta_data, public_fns,
                                   ddt_source_module=None, protected_std_names=None,
                                   host_std_names=None, ccpp_mod=None):
        """Build a single combined CCPP cap ModuleOp for all suites.

        Generates one module whose lifecycle subroutines use nested if/else chains
        to dispatch to the appropriate suite cap subroutine.
        """
        all_suite_names = list(suite_descriptions.keys())

        camel_name = (
            self.host_name
            if self.host_name
            else self._derive_camel_case_name(all_suite_names[0])
        )

        # Module name uses the same CamelCase prefix as the subroutine names
        # so that 'module HelloWorld_ccpp_cap' matches 'use HelloWorld_ccpp_cap'
        # in host model files.  --host-name can still override when needed.
        mod_name = camel_name + "_ccpp_cap"

        char_base = TypeConversions.getBaseType("character")
        int_base = TypeConversions.getBaseType("integer")
        suite_name_type = memref.MemRefType(char_base, [DYNAMIC_INDEX])
        errmsg_type = memref.MemRefType(char_base, [512])
        errflg_type = memref.MemRefType(int_base, [])

        common = dict(
            suite_name_type=suite_name_type,
            errmsg_type=errmsg_type,
            errflg_type=errflg_type,
            char_base=char_base,
            int_base=int_base,
            public_fns=public_fns,
        )

        lifecycle_specs = [
            ("_ccpp_physics_register", "_register", "_suite_register", None),
            ("_ccpp_physics_initialize", "_init", "_suite_initialize", None),
            ("_ccpp_physics_finalize", "_finalize", "_suite_finalize", None),
            ("_ccpp_physics_timestep_initial", "_timestep_initialize", "_suite_timestep_initial", None),
            ("_ccpp_physics_timestep_final", "_timestep_finalize", "_suite_timestep_final", None),
            # Run: per-group dispatch — each group calls its own suite cap function.
            ("_ccpp_physics_run", None, "_suite_", "__per_group__"),
        ]

        all_globals: list = []
        all_definitions: list = []
        all_declarations: list = []
        # Shared across ALL function calls (lifecycle AND run) to avoid duplicate GlobalOps.
        # Both lifecycle and run functions can reference the same host variables (e.g.
        # a DDT instance used in the run function may also appear in lifecycle functions).
        shared_seen_host_globals: set = set()

        # ── Build cap_var_map: interstitial DDT values returned from lifecycle ──
        # These need module-level storage in the cap so they persist between calls.
        # Format: standard_name → (var_name, mlir_type, fortran_type_str)
        # Also build host_var_map_lc for identifying host-var returns (write-back).
        cap_var_map: dict = {}
        # MODULE only: write-back targets (like num_model_times) live in MODULE
        # tables.  HOST-type tables are caller-provided interfaces, not modules.
        host_var_map_lc = self._build_host_var_map(meta_data, include_host=False)

        # Detect the ccpp_info_t pattern: HOST table contains a variable with
        # standard_name = host_standard_ccpp_type (e.g. ddthost).  When present,
        # lifecycle and run functions accept a single ccpp_info_t inout arg that
        # bundles errmsg/errflg and (for run) col_start/col_end.
        from xdsl_ccpp.dialects.ccpp_utils import DerivedType as _DerivedType
        ccpp_info_type = None
        ccpp_info_module_name = None
        for _tbl, _props in meta_data.items():
            if _props.getAttr("type") != CCPPType.HOST:
                continue
            if _tbl not in _props.arg_tables:
                continue
            for _var in _props.getArgTable(_tbl).getFunctionArguments():
                if (
                    _var.hasAttr("standard_name")
                    and _var.getAttr("standard_name").lower() == "host_standard_ccpp_type"
                    and _var.hasAttr("type")
                ):
                    _ddt_type_name = _var.getAttr("type")
                    _src = (ddt_source_module or {}).get(_ddt_type_name)
                    if _src:
                        ccpp_info_type = memref.MemRefType(
                            _DerivedType(_ddt_type_name), []
                        )
                        ccpp_info_module_name = _src
                        # The USE stub for ccpp_info_t is emitted by the DDT
                        # type loop below (it scans all arg table types).
                    break
            if ccpp_info_type is not None:
                break

        errmsg_type_tmp = memref.MemRefType(
            TypeConversions.getBaseType("character"), [512]
        )
        errflg_type_tmp = memref.MemRefType(
            TypeConversions.getBaseType("integer"), []
        )
        for _, table_postfix, callee_suffix, suite_part in lifecycle_specs:
            if suite_part is not None or table_postfix is None:
                continue  # only init/finalize produce cap-owned returns
            for suite_name, suite_desc in suite_descriptions.items():
                suite_callee = suite_name + callee_suffix
                if suite_callee not in public_fns:
                    continue
                scheme_names_lc = [
                    s.attributes["name"]
                    for g in suite_desc for s in g
                ]
                ret_info = self._get_suite_lifecycle_ret_info(
                    scheme_names_lc, meta_data, table_postfix
                )
                for ret_type, arg_name, std_name in ret_info:
                    if ret_type in (errmsg_type_tmp, errflg_type_tmp):
                        continue
                    if std_name in host_var_map_lc:
                        continue  # host var — will be written back, not cap-owned
                    # DDT interstitials (e.g. vmr_type) are now declared at suite
                    # cap module scope by generateSuiteModuleOp.  The top-level cap
                    # no longer needs to track or pass them via cap_var_map.

        for fn_suffix, table_postfix, callee_suffix, suite_part in lifecycle_specs:
            if suite_part is not None:
                # Run function: one dispatch entry per XML group, all pointing to
                # the combined _suite_physics callee.  This correctly maps each
                # group name (e.g. 'physics1', 'physics2') to the same combined
                # function while keeping per-group state intact at module scope.
                suite_run_entries = []
                for suite_name, suite_desc in suite_descriptions.items():
                    for group in suite_desc:
                        group_name = group.attributes["name"]
                        # Per-group callee: e.g. temp_suite_suite_physics1
                        suite_callee = suite_name + callee_suffix + group_name
                        if suite_callee not in public_fns:
                            continue
                        # Only this group's scheme names — matches the per-group callee's signature
                        group_scheme_names = [
                            scheme.attributes["name"] for scheme in group
                        ]
                        suite_run_entries.append(
                            (suite_name, group_name, suite_callee, group_scheme_names)
                        )

                if not suite_run_entries:
                    continue

                cap_fn, decls, host_global_ops = self._generate_run_fn(
                    fn_name=camel_name + fn_suffix,
                    suite_run_entries=suite_run_entries,
                    meta_data=meta_data,
                    cap_var_map=cap_var_map,
                    seen_host_globals=shared_seen_host_globals,
                    ccpp_info_type=ccpp_info_type,
                    ccpp_info_module=ccpp_info_module_name,
                    **common,
                )
                all_globals.extend(host_global_ops)
                all_declarations.extend(decls)
            else:
                # Lifecycle function: collect per-suite callee info
                suite_entries = []
                for suite_name, suite_desc in suite_descriptions.items():
                    suite_callee = suite_name + callee_suffix
                    if suite_callee not in public_fns:
                        continue
                    scheme_names = [
                        scheme.attributes["name"]
                        for group in suite_desc
                        for scheme in group
                    ]
                    if table_postfix is not None:
                        ret_info = self._get_suite_lifecycle_ret_info(
                            scheme_names, meta_data, table_postfix
                        )
                        call_ret_types = [t for t, _n, _s in ret_info]
                        # If no scheme-level outputs (e.g. register when no scheme
                        # has a _register entry), fall back to the callee's signature
                        # so errmsg/errflg are included.
                        if not call_ret_types:
                            _, call_ret_types, _, _ = public_fns[suite_callee]
                            ret_info = [(t, None, None) for t in call_ret_types]
                    else:
                        _, call_ret_types, _, _ = public_fns[suite_callee]
                        ret_info = [(t, None, None) for t in call_ret_types]
                    # entry_postfix is the scheme-level entry point suffix
                    # (e.g. "_init" for initialize, "_finalize" for finalize,
                    # None for timestep functions that have no host inputs).
                    entry_postfix = table_postfix
                    suite_entries.append(
                        (suite_name, suite_callee, call_ret_types,
                         scheme_names, entry_postfix, ret_info)
                    )

                if not suite_entries:
                    continue

                cap_fn, decls, lc_host_ops = self._generate_lifecycle_fn(
                    fn_name=camel_name + fn_suffix,
                    suite_entries=suite_entries,
                    meta_data=meta_data,
                    seen_host_globals=shared_seen_host_globals,
                    cap_var_map=cap_var_map,
                    host_var_map_lc=host_var_map_lc,
                    ccpp_info_type=ccpp_info_type,
                    ccpp_info_module=ccpp_info_module_name,
                    **common,
                )
                all_globals.extend(lc_host_ops)
                all_declarations.extend(decls)

            all_definitions.append(cap_fn)

        # Generate ccpp_physics_suite_list listing ALL suite names.
        inner_char_type = memref.MemRefType(i8, [DYNAMIC_INDEX])
        allocatable_type = memref.MemRefType(inner_char_type, [])
        suite_list_block = Block(arg_types=[allocatable_type])
        suite_list_block.args[0].name_hint = "suites"

        body_ops = []
        for sn in all_suite_names:
            str_global_name = f"str_{sn}"
            str_len = len(sn)
            arr_type = llvm.LLVMArrayType.from_size_and_type(str_len, i8)

            all_globals.append(
                llvm.GlobalOp(
                    arr_type,
                    str_global_name,
                    "internal",
                    constant=True,
                    value=StringAttr(sn),
                )
            )

            str_len_const = arith.ConstantOp(
                IntegerAttr(str_len, IndexType()), IndexType()
            )
            str_alloc = memref.AllocOp([str_len_const.result], [], inner_char_type)
            addr_op = llvm.AddressOfOp(str_global_name, llvm.LLVMPointerType())
            load_op = llvm.LoadOp(addr_op, arr_type)
            set_str_op = SetStringOp(str_alloc.memref, load_op.dereferenced_value)
            store_ref_op = memref.StoreOp.get(
                str_alloc.memref, suite_list_block.args[0], []
            )
            body_ops.extend(
                [str_len_const, str_alloc, addr_op, load_op, set_str_op, store_ref_op]
            )

        suite_list_block.add_ops([*body_ops, func.ReturnOp()])
        suite_list_region = Region()
        suite_list_region.add_block(suite_list_block)
        suite_list_fn = func.FuncOp(
            "ccpp_physics_suite_list",
            builtin.FunctionType.from_lists([allocatable_type], []),
            suite_list_region,
            visibility="public",
        )
        all_definitions.append(suite_list_fn)

        # Generate ccpp_physics_suite_part_list — use actual XML group names per suite.
        suite_part_entries = [
            (sn, [grp.attributes["name"] for grp in suite_descriptions[sn]])
            for sn in all_suite_names
        ]

        suite_part_list_fn, part_global_ops = self._generate_suite_part_list_fn(
            suite_part_entries=suite_part_entries,
            inner_char_type=inner_char_type,
            allocatable_type=allocatable_type,
            suite_name_type=suite_name_type,
            errmsg_type=errmsg_type,
            errflg_type=errflg_type,
            char_base=char_base,
            int_base=int_base,
        )
        all_globals.extend(part_global_ops)
        all_definitions.append(suite_part_list_fn)
        suite_vars_op = self._build_suite_variables_fn(
            suite_descriptions, ccpp_mod,
            host_std_names or set(),
            protected_std_names or set(),
        )
        all_definitions.append(suite_vars_op)

        # Emit USE-association stubs for DDT types used in any scheme across all suites.
        if ddt_source_module:
            primitive_types = {"real", "integer", "character", "logical", "complex"}
            seen_type_imports: set[str] = set()
            for props in meta_data.values():
                for arg_table in props.arg_tables.values():
                    for arg in arg_table.getFunctionArguments():
                        if not arg.hasAttr("type"):
                            continue
                        arg_type = arg.getAttr("type")
                        if arg_type in primitive_types or arg_type in seen_type_imports:
                            continue
                        mod = ddt_source_module.get(arg_type)
                        if mod is None:
                            continue
                        seen_type_imports.add(arg_type)
                        stub = llvm.GlobalOp(
                            llvm.LLVMArrayType.from_size_and_type(0, i8),
                            arg_type,
                            "internal",
                        )
                        stub.attributes["module"] = StringAttr(mod)
                        all_globals.append(stub)

        module_ops = all_globals + all_definitions + all_declarations

        return builtin.ModuleOp(
            module_ops,
            sym_name=builtin.StringAttr(mod_name),
        )

    def apply(self, ctx: Context, op: builtin.ModuleOp) -> None:
        ccpp_mod = self.find_ccpp_module(op.body.block.ops)
        assert ccpp_mod is not None

        # Build Python descriptor objects from the CCPP metadata IR
        bmdd = BuildMetaDataDescriptions()
        bmdd.traverse(ccpp_mod)
        meta_data_descriptions = bmdd.meta_data

        # Build the suite hierarchy descriptors
        bsd = BuildSchemeDescription()
        bsd.traverse(ccpp_mod)
        suite_descriptions = bsd.schemes

        # Collect public functions from suite cap modules already in the IR
        public_fns = self._collect_public_suite_functions(op.body.block.ops)

        # Build DDT-type-name → Fortran-module-name map (shared utility).
        ddt_source_module = collect_ddt_source_modules(ccpp_mod)

        # Build set of ALL standard_names provided by the host model (from
        # non-scheme tables in the IR).  Used in _build_suite_variables_fn to
        # exclude scheme-internal args that have no host counterpart.
        host_std_names: set[str] = set()
        for tbl_op in ccpp_mod.body.ops:
            if not isa(tbl_op, ccpp.TablePropertiesOp):
                continue
            if tbl_op.table_type.data == "scheme":
                continue
            for arg_table_op in tbl_op.body.ops:
                if not isa(arg_table_op, ccpp.ArgumentTableOp):
                    continue
                for arg_op in arg_table_op.body.ops:
                    if not isa(arg_op, ccpp.ArgumentOp):
                        continue
                    if arg_op.standard_name is not None:
                        host_std_names.add(arg_op.standard_name.data.lower())

        # Build set of protected host-variable standard_names.
        # Protected variables (e.g. vertical_layer_dimension, horizontal_dimension)
        # are framework-managed and excluded from ccpp_physics_suite_variables lists.
        protected_std_names: set[str] = set()
        for tbl_op in ccpp_mod.body.ops:
            if not isa(tbl_op, ccpp.TablePropertiesOp):
                continue
            if tbl_op.table_type.data not in ("module", "host", "ddt"):
                continue
            for arg_table_op in tbl_op.body.ops:
                if not isa(arg_table_op, ccpp.ArgumentTableOp):
                    continue
                for arg_op in arg_table_op.body.ops:
                    if not isa(arg_op, ccpp.ArgumentOp):
                        continue
                    if (arg_op.properties.get("protected") is not None
                            and arg_op.standard_name is not None):
                        protected_std_names.add(
                            arg_op.standard_name.data.lower()
                        )

        # Generate ONE combined CCPP cap module for all suites
        cap_mod = self._generate_ccpp_cap_module(
            suite_descriptions, meta_data_descriptions, public_fns,
            ddt_source_module=ddt_source_module,
            protected_std_names=protected_std_names,
            host_std_names=host_std_names,
            ccpp_mod=ccpp_mod,
        )
        op.body.block.add_op(cap_mod)
