#!/bin/bash

export SUITESF='examples/helloworld/hello_world_suite.xml'
export SCHEMEF='examples/helloworld/hello_scheme.meta,examples/helloworld/temp_adjust.meta'
export HOSTF='examples/helloworld/hello_world_host.meta,examples/helloworld/hello_world_mod.meta'
  
ccpp_xdsl --suites $SUITESF --scheme-files $SCHEMEF --host-files $HOSTF -o examples/helloworld/ --kind-map kind_dyn:REAL32
#ccpp_xdsl --suites $SUITESF --scheme-files $SCHEMEF --host-files $HOSTF -o examples/helloworld/ --kind-map kind_dyn:REAL32 --debug
