// Plain C++ driver for the Kessler microphysics example.
// Calls xdsl-ccpp BIND(C) physics caps generated with --bind-c.
// Data lives in Fortran's kessler_host_mod; this driver controls the CCPP
// lifecycle and measures wall-clock time with std::chrono.
//
// Build via:  make -f examples/kessler/Makefile cpp
// Run via:    make -f examples/kessler/Makefile run_cpp

#include "Kessler_ccpp_cap.h"  // generated by xdsl-ccpp --bind-c

#include <chrono>
#include <cstdio>
#include <cstring>

// BIND(C) bridges from kessler_host_init_c.F90.
extern "C" {
    void kessler_host_init_data();
    void kessler_host_print_results(double elapsed_s);
}

static constexpr int ERRMSG_LEN = 512;

static void check(const char* label, const char* errmsg, int errflg) {
    if (errflg != 0) {
        std::fprintf(stderr, "%s error: %s\n", label, errmsg);
        std::exit(1);
    }
}

int main() {
    char errmsg[ERRMSG_LEN];
    int  errflg = 0;

    // Initialise kessler_host_mod: grid dimensions, physical constants,
    // allocate arrays, Box-Muller fill.
    kessler_host_init_data();

    // Register the suite.
    std::memset(errmsg, 0, sizeof(errmsg));
    Kessler_ccpp_physics_register("kessler_suite", errmsg, &errflg);
    check("register", errmsg, errflg);

    // Initialise physics constants (kessler_init, kessler_update_init).
    std::memset(errmsg, 0, sizeof(errmsg));
    Kessler_ccpp_physics_initialize("kessler_suite", errmsg, &errflg);
    check("initialize", errmsg, errflg);

    // Timestep initial: copies temp → temp_prev, zeroes ttend_t.
    std::memset(errmsg, 0, sizeof(errmsg));
    Kessler_ccpp_physics_timestep_initial("kessler_suite", errmsg, &errflg);
    check("timestep_initial", errmsg, errflg);

    // Run physics (timed).
    std::memset(errmsg, 0, sizeof(errmsg));
    auto t_start = std::chrono::high_resolution_clock::now();
    Kessler_ccpp_physics_run("kessler_suite", "physics", 1, 1000, errmsg, &errflg);
    auto t_end   = std::chrono::high_resolution_clock::now();
    check("run", errmsg, errflg);

    double elapsed_s =
        std::chrono::duration<double>(t_end - t_start).count();

    // Timestep final: computes dry static energy.
    std::memset(errmsg, 0, sizeof(errmsg));
    Kessler_ccpp_physics_timestep_final("kessler_suite", errmsg, &errflg);
    check("timestep_final", errmsg, errflg);

    // Finalise.
    std::memset(errmsg, 0, sizeof(errmsg));
    Kessler_ccpp_physics_finalize("kessler_suite", errmsg, &errflg);
    check("finalize", errmsg, errflg);

    // Print sums and elapsed time (delegates to kessler_host_mod::print_results).
    kessler_host_print_results(elapsed_s);

    return 0;
}
