"""Shared helpers used across ccpp_cap.py, cpp_interop.py, lifecycle_cap.py, and
constituent_cap.py.

A neutral leaf module with no dependency on any of the cap-generation files,
so those files can freely import from here without creating an import cycle
(ccpp_cap.py calls into lifecycle_cap.py/constituent_cap.py directly, and all
three need these same helpers, which previously lived in ccpp_cap.py itself).
"""

from xdsl_ccpp.transforms.util.ccpp_descriptors import CCPPType
from xdsl_ccpp.transforms.util.typing import TypeConversions

_CCPP_CONSTITUENT_MOD = "ccpp_constituent_prop_mod"

_CONSTITUENT_DDT_NAME = "ccpp_constituent_properties_t"


def _bare(name: str) -> str:
    """Strip __alloc, __opt, or __in suffix from an arg name hint to get the bare Fortran name."""
    if name.endswith("__alloc"):
        return name[:-7]
    if name.endswith("__opt"):
        return name[:-5]
    if name.endswith("__in"):
        return name[:-4]
    return name


def _build_host_var_map(meta_data, include_host: bool = True) -> dict:
    """Build a standard_name → (var_name, table_name) map from host metadata.

    Args:
        meta_data:    descriptor dict from BuildMetaDataDescriptions.
        include_host: when True (default) includes both MODULE and HOST type
                      tables.  When False, only MODULE type tables are scanned.
                      HOST-type variables are ephemeral values passed directly
                      by the host caller; MODULE-type variables are accessible
                      via USE statements.

    Returns:
        dict mapping lowercase standard_name → (local_var_name, table_name).
    """
    table_types = (
        (CCPPType.MODULE, CCPPType.HOST) if include_host else (CCPPType.MODULE,)
    )
    result: dict = {}
    for tbl_name, props in meta_data.items():
        if props.getAttr("type") not in table_types:
            continue
        if tbl_name not in props.arg_tables:
            continue
        for var in props.getArgTable(tbl_name).getFunctionArguments():
            if var.hasAttr("standard_name"):
                result[var.getAttr("standard_name").lower()] = (var.name, tbl_name)
    return result


def _is_framework_managed(a) -> bool:
    """True for suite-cap-owned variables: interstitials of any type,
    and advected/allocatable real arrays."""
    if a.hasAttr("is_interstitial"):
        return True
    if a.getAttr("type") != "real":
        return False
    if not (a.hasAttr("dimensions") and a.getAttr("dimensions") > 0):
        return False
    return a.hasAttr("advected") or a.hasAttr("allocatable")


def _get_suite_lifecycle_ret_info(scheme_names, meta_data, table_postfix):
    """Return [(mlir_type, arg_name, standard_name)] for intent=out scalar args.

    Applies the same filters as suite_cap.py's ``output_arg_list`` so the
    returned types match the actual FuncOp return signature generated by the
    suite cap:
    - intent=out only
    - Scalar (dimensions = 0 or absent) — array outs are block args, not returns
    - Not allocatable — those become __alloc block args
    - Not interstitial — framework-managed vars are not suite cap outputs
    """
    all_out_args = {}
    for scheme_name in scheme_names:
        table_name = scheme_name + table_postfix
        if scheme_name not in meta_data:
            continue
        if table_name not in meta_data[scheme_name].arg_tables:
            continue
        arg_table = meta_data[scheme_name].getArgTable(table_name)
        for fn_arg in arg_table.getFunctionArguments():
            has_dims = fn_arg.hasAttr("dimensions") and fn_arg.getAttr("dimensions") > 0
            # _is_framework_managed's array-shaped branch requires dims > 0,
            # which the `not has_dims` filter below already excludes here — so
            # for every arg that can reach that filter, this call reduces to
            # exactly the is_interstitial check it used to hand-roll.
            is_framework_managed = _is_framework_managed(fn_arg)
            # Deduplicate by standard_name so different local names for the
            # same logical arg (e.g. errflg vs errcode for ccpp_error_code)
            # don't produce duplicate return types.
            _dedup_key = (
                fn_arg.getAttr("standard_name").lower()
                if fn_arg.hasAttr("standard_name")
                else fn_arg.name
            )
            if (
                fn_arg.getAttr("intent") == "out"
                and _dedup_key not in all_out_args
                and not has_dims
                and not fn_arg.hasAttr("allocatable")
                and not is_framework_managed
            ):
                all_out_args[_dedup_key] = fn_arg

    result = []
    for arg in all_out_args.values():
        mlir_type = TypeConversions.convert(
            arg.getAttr("type"),
            arg.getAttr("kind") if arg.hasAttr("kind") else None,
            0,
        )
        raw = arg.getAttr("standard_name") if arg.hasAttr("standard_name") else None
        std_name = raw.lower() if raw else None
        result.append((mlir_type, arg.name, std_name))
    return result
