// Generated by xdsl-ccpp. C++ ergonomics wrapper for Ddthost_ccpp_chost_cap.
// Array arguments are column-major (Fortran order).
#pragma once
#include <string>
#include <vector>
#include "Ddthost_ccpp_chost_cap.h"

namespace Ddthost_chost {

struct Status {
    int         code;
    std::string message;
    bool ok() const { return code == 0; }
};

// ── register ────────────────────────────────────────────────────────────────

inline Status do_register() {
    char   errmsg[512]      = {};
    int    errflg           = 0;
    Ddthost_chost_physics_register(errmsg, &errflg);
    return {errflg, errflg ? errmsg : ""};
}

// ── initialize ──────────────────────────────────────────────────────────────

struct InitializeArgs {
    int              ncols;
    int              vmr_nvmr;
    int              ccpp_info_col_start;
    int              ccpp_info_col_end;
    int              ccpp_info_errflg;
    double*          vmr_vmr_array;
};

inline Status initialize(const InitializeArgs& a) {
    char   errmsg[512]      = {};
    int    errflg           = 0;
    Ddthost_chost_physics_initialize(
        a.ncols, a.vmr_nvmr, a.ccpp_info_col_start, a.ccpp_info_col_end,
        a.ccpp_info_errflg, a.vmr_vmr_array, errmsg, &errflg
    );
    return {errflg, errflg ? errmsg : ""};
}

// ── finalize ────────────────────────────────────────────────────────────────

inline Status finalize() {
    char   errmsg[512]      = {};
    int    errflg           = 0;
    Ddthost_chost_physics_finalize(errmsg, &errflg);
    return {errflg, errflg ? errmsg : ""};
}

// ── timestep_initial ────────────────────────────────────────────────────────

inline Status timestep_initial() {
    char   errmsg[512]      = {};
    int    errflg           = 0;
    Ddthost_chost_physics_timestep_initial(errmsg, &errflg);
    return {errflg, errflg ? errmsg : ""};
}

// ── timestep_final ──────────────────────────────────────────────────────────

struct TimestepFinalArgs {
    int              ncols;
    int              vmr_nvmr;
    const double*    vmr_vmr_array;
};

inline Status timestep_final(const TimestepFinalArgs& a) {
    char   errmsg[512]      = {};
    int    errflg           = 0;
    Ddthost_chost_physics_timestep_final(
        a.ncols, a.vmr_nvmr, a.vmr_vmr_array, errmsg,
        &errflg
    );
    return {errflg, errflg ? errmsg : ""};
}

// ── run ─────────────────────────────────────────────────────────────────────

struct RunArgs {
    int              ncols;
    int              vmr_nvmr;
    int              col_start;
    int              col_end;
    const double*    O3;
    const double*    HNO3;
    double*          vmr_vmr_array;
};

inline Status run(const RunArgs& a) {
    char   errmsg[512]      = {};
    int    errflg           = 0;
    Ddthost_chost_physics_run(
        a.ncols, a.vmr_nvmr, a.col_start, a.col_end,
        a.O3, a.HNO3, a.vmr_vmr_array, errmsg,
        &errflg
    );
    return {errflg, errflg ? errmsg : ""};
}

// ── State ─────────────────────────────────────────────────────────────────────

struct State {
    int              ncols = 0;
    int              vmr_nvmr = 0;
    int              ccpp_info_col_start = 0;
    int              ccpp_info_col_end = 0;
    int              ccpp_info_errflg = 0;
    double*          vmr_vmr_array = nullptr;
    double*          O3 = nullptr;
    double*          HNO3 = nullptr;

    State(int ncols = 0, int vmr_nvmr = 0)
        : ncols(ncols), vmr_nvmr(vmr_nvmr) {}

    // Allocate all array fields from internal storage.
    // Set ncol (and nz for 2-D arrays) before calling.
    void allocate() {
        _vmr_vmr_array.assign(static_cast<std::size_t>(ncols) * vmr_nvmr, 0);
        vmr_vmr_array = _vmr_vmr_array.data();
        _O3.assign(static_cast<std::size_t>(ncols), 0);
        O3 = _O3.data();
        _HNO3.assign(static_cast<std::size_t>(ncols), 0);
        HNO3 = _HNO3.data();
    }

private:
    std::vector<double> _vmr_vmr_array;
    std::vector<double> _O3;
    std::vector<double> _HNO3;
};

inline Status initialize(const State& s) {
    return initialize({
        .ncols=s.ncols,
        .vmr_nvmr=s.vmr_nvmr,
        .ccpp_info_col_start=s.ccpp_info_col_start,
        .ccpp_info_col_end=s.ccpp_info_col_end,
        .ccpp_info_errflg=s.ccpp_info_errflg,
        .vmr_vmr_array=s.vmr_vmr_array,
    });
}

inline Status timestep_final(const State& s) {
    return timestep_final({
        .ncols=s.ncols,
        .vmr_nvmr=s.vmr_nvmr,
        .vmr_vmr_array=s.vmr_vmr_array,
    });
}

inline Status run(const State& s, int col_start, int col_end) {
    return run({
        .ncols=s.ncols,
        .vmr_nvmr=s.vmr_nvmr,
        .col_start=col_start,
        .col_end=col_end,
        .O3=s.O3,
        .HNO3=s.HNO3,
        .vmr_vmr_array=s.vmr_vmr_array,
    });
}

} // namespace Ddthost_chost
