// Generated by xdsl-ccpp. Array arguments are column-major (Fortran order).
// Pass Kokkos::View with LayoutLeft, or transpose before calling.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif

void Ddthost_ccpp_physics_register(
    const char*      suite_name,
    double*          ccpp_info 
);

void Ddthost_ccpp_physics_initialize(
    const char*      suite_name,
    double*          ccpp_info 
);

void Ddthost_ccpp_physics_finalize(
    const char*      suite_name,
    double*          ccpp_info 
);

void Ddthost_ccpp_physics_timestep_initial(
    const char*      suite_name,
    double*          ccpp_info 
);

void Ddthost_ccpp_physics_timestep_final(
    const char*      suite_name,
    double*          ccpp_info 
);

void Ddthost_ccpp_physics_run(
    const char*      suite_name,
    const char*      suite_part,
    double*          ccpp_info,
    double*          O3,
    double*          HNO3 
);

#ifdef __cplusplus
}
#endif
