// Generated by xdsl-ccpp. Array arguments are column-major (Fortran order).
// Pass Kokkos::View with LayoutLeft, or transpose before calling.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif

void Ddthost_chost_physics_register(
    char*            errmsg,
    int*             errflg 
);

void Ddthost_chost_physics_initialize(
    int              ncols,
    int              vmr_nvmr,
    int              ccpp_info_col_start,
    int              ccpp_info_col_end,
    int              ccpp_info_errflg,
    double*          vmr_vmr_array,
    char*            errmsg,
    int*             errflg 
);

void Ddthost_chost_physics_finalize(
    char*            errmsg,
    int*             errflg 
);

void Ddthost_chost_physics_timestep_initial(
    char*            errmsg,
    int*             errflg 
);

void Ddthost_chost_physics_timestep_final(
    int              ncols,
    int              vmr_nvmr,
    const double*    vmr_vmr_array,
    char*            errmsg,
    int*             errflg 
);

void Ddthost_chost_physics_run(
    int              ncols,
    int              vmr_nvmr,
    int              col_start,
    int              col_end,
    const double*    O3,
    const double*    HNO3,
    double*          vmr_vmr_array,
    char*            errmsg,
    int*             errflg 
);

#ifdef __cplusplus
}
#endif
